/** Headless annual projection contracts. Values are nominal within the ledger; inflationIndex translates to the selected base-year purchasing power. */
import type {SavingsStrategy} from '../types/index.js';
import type {HsaElection} from '../cashflow/advantaged.js';
import type {SeppInput} from '../bridge/sepp.js';
import type {PretaxSource,PretaxSourceBalance,PretaxPerson} from '../accounts/pretax.js';
export type Promotion={year:number;salary?:number;percent?:number};
export type CareerBreak={start:number;end:number;payFraction:number};
export type ConversionLot={year:number;amount:number;taxableAmount?:number;documented?:boolean};
export type ProjectionPerson={id:string;name:string;birthYear:number;birthDate?:string;workStart:number;retireYear:number;salary:number;salaryBaseYear?:number;salaryGrowth:number;salaryGrowthUnit?:string;employee401k:number;employee401kMode?:string;employee401kPercent?:number;rothContribution:number;brokerageContribution:number;matchImmediate:number;matchGraded:number;employmentStart:number;traditional:number;unvested:number;roth:number;rothBasis:number;rothOpenYear:number;brokerage:number;brokerageBasis:number;cash:number;rothBasisDocumented?:boolean;rothConversionLots?:ConversionLot[];promotions?:Promotion[];careerBreaks?:CareerBreak[];spousalIRA?:boolean;savingsStrategy?:SavingsStrategy;savingsAnnual?:number;brokerageReturnDrag?:number;brokerageTaxTreatment?:string;cashNominalReturn?:number;retirementBrokerageReturnDrag?:number;socialSecurityAnnual?:number;socialSecurityStartYear?:number;pretaxEarlyAccess?:'ira'|'after_separation'|'unavailable';penaltyException?:boolean;pretaxSources?:PretaxSource[];penaltyExceptions?:PretaxPerson['penaltyExceptions'];hsaBalance?:number;hsaQualifiedExpensesAnnual?:number;hsa?:HsaElection;rothMode?:string;backdoor?:{verified:boolean;pretaxIraBalance:number;aftertaxIraBasis:number};megaBackdoor?:{enabled:boolean;verified:boolean;afterTaxAllowed:boolean;rothIraRolloverAllowed:boolean;annual:number};sepp?:{enabled:boolean;input:SeppInput;stopYear?:number};[key:string]:unknown};
export type Expense={id:string;name:string;owner:string;annual:number;start:number;end:number;inflate:boolean;essential?:boolean;phase?:string};
export type Assumption={id:string;text:string;confirmed:boolean;source?:string;status?:string;reviewDate?:string};
export type RetirementBudget={enabled:boolean;annual:number;dollarMode:string;taxes:string;healthcare:string;minimumLiving:number};
export type Housing={mode:string;moveYear:number;rent:number;jointRent:number;jointRentYear:number;tnRent:number;rentGrowth:number;buyYear:number;price:number;down:number;rate:number;term:number;closing:number;selling:number;appreciation:number;propertyTax:number;insurance:number;maintenance:number;hoa:number;relocation:number;movingCost:number;[key:string]:unknown};
export type Plan={schema:number;name:string;startYear:number;baseYear:number;endYear:number;jointYear:number;people:ProjectionPerson[];expenses:Expense[];housing:Housing;overrides:Record<number,Record<string,number>>;assumptions:Assumption[];inflation:number;taxInflation:number;stockReturn:number;stockVol:number;bondReturn:number;bondVol:number;correlation:number;cashReturn:number;stockWeight:number;fees:number;dividendYield:number;surplus:string;cashReserve:number;cashReserveWorking?:number;cashReserveMode?:string;reserveMonths?:number;strategy:'fixed'|'percent'|'guardrails';withdrawalRate:number;spendingFloor:number;conversionAnnual:number;conversionStart:number;conversionEnd:number;capConversions:boolean;acaFpl:number;acaTarget:number;acaUpper:number;acaStart:number;acaEnd:number;returnUnit?:string;allocationMode?:string;retirementStockWeight?:number;retirementStockReturn?:number;retirementBondReturn?:number;retirementCashReturn?:number;cashNominalReturn?:number;stockReturnMean?:string;bondYield?:number;retirementBudget?:RetirementBudget;withdrawalPolicy?:{allowPenalties?:boolean;order?:'taxable_first'|'roth_first'|'pretax_first';earlyPreference?:'conversion_first'|'traditional_first'|'roth_first'};healthcare?:HealthConfig;enforceCashBuffer?:boolean;relaxedConversionYears?:number[];[key:string]:unknown};
export type Account={id:string;traditional:number;unvested:number;roth:number;rothBasis:number;brokerage:number;brokerageBasis:number;cash:number;hsa:number;sepp:number;lots:ConversionLot[];gradedPool:number;pretaxSources?:PretaxSourceBalance[];legacyIraBalance?:number;[key:string]:unknown};
export type PeopleFlow={id:string;name:string;wages:number;employee401k:number;employeeHsa:number;employerHsa:number;megaBackdoor:number;seppDistribution:number;employer:number;payrollTax:number;federalTax:number;earnedIncomeAfterTax:number;takeHome:number;rothAdded:number;taxableDeposits:number;withdrawals:number;penalty:number;personalSpending:number;[key:string]:unknown};
export type AccessBreakdown={cash:number;taxable:number;basis:number;seasoned:number;traditional:number;accessible:number;[key:string]:unknown};
export type BudgetRow={target:number;housing:number;includedTax:number;includedHealth:number;living:number;outside:number;purchaseUpfront:number;additional:number;overrun:number};
export type CoverageKind='parent'|'employer'|'marketplace'|'medicare'|'uninsured';
export type CoverageMonths=Partial<Record<CoverageKind,number>>;
export type HealthPerson={id:string;parentType:string;parentAnnual:number;employerAnnual:number;marketplaceMonthly:number;benchmarkMonthly:number;outOfPocketAnnual:number;eligibility:string;partDMonthly:number;supplementMonthly:number;partAMonthly:number;coverageOverrides:{year:number;months:CoverageMonths}[]};
export type HealthConfig={enabled:boolean;premiumGrowth:number;fplGrowth:number;medicareGrowth:number;replacedExpenseIds:string[];people:HealthPerson[];lookback?:Record<number,{magi:number;byPerson:number[];joint:boolean}>};
export type HealthRow={cost:number;credit?:number;people:{id:string;name:string;months:CoverageMonths;cost:number;credit:number;irmaaTier:number|null}[];flags:string[];[key:string]:unknown};
export type HsaReview={employeeRequested:number[];employeeFunded:number[];eligibleMonths:number[];contributionLimits:number[];employeeCapped:number[];employerCapped:number[];direct:number[];deductible:number[];payrollExcluded:number[];fundingShortfall:number;flags:string[]};
export type ProjectionRow={hsaReview?:HsaReview;year:number;age:number;joint:boolean;retired:boolean;inflationIndex:number;wages:number;otherIncome:number;socialSecurity:number;employee401k:number;employeeHsa:number;employerHsa:number;megaBackdoor:number;seppDistribution:number;payrollTax:number;federalTax:number;ordinaryIncomeTax:number;earlyWithdrawalPenalty:number;penaltyFallbackUsed:boolean;spending:number;personalSpending:number;totalOutgo:number;upfront:number;saleProceeds:number;shortfall:number;spendingFunded:number;cashAfterFunding:number;unfundedAfterWithdrawals:number;reserveShortfall:number;rothAdded:number;brokerAdded:number;investedSurplus:number;employer:number;conversion:number;openingPortfolio:number;openingRealPortfolio:number;growth:number;adjustments:number;forfeiture:number;portfolio:number;realPortfolio:number;reconciliation:number;magi:number;acaLimit:number;accessible:number;netWorth:number;homeEquity:number;accounts:Account[];openingAccounts:Account[];peopleFlow:PeopleFlow[];wagesByPerson:number[];accessByPerson:AccessBreakdown[];budget:BudgetRow|null;healthcare:HealthRow;[key:string]:unknown};
export type ProjectionResult={rows:ProjectionRow[];firstFailure:number|null;success:boolean;retirement:ProjectionRow|null;terminal:ProjectionRow|undefined;[key:string]:unknown};

export interface MarketReturn {stock:number;bond:number;inflation:number;cash?:number}
export interface RetirementEnvelope {target:number;minimumLiving:number;taxes:string;healthcare:string;plannedTarget?:number}
export interface HousingYear {year:number;cost:number;upfront:number;saleProceeds:number;home:number;debt:number;equity:number;interest:number;principal:number;operating:number;owns:boolean;relocation:number;moving:number}
export interface TaxSummary {total:number;ordinaryTax:number;capitalTax:number;niit:number;magi:number;agi:number;taxableBenefits:number;embeddedDistributionTax:number}
export interface HouseholdTax extends TaxSummary {incomeTax:number;penalty:number;agiByPerson:number[];magiByPerson:number[];federalByPerson:number[]}
export type EffectiveSavingsStrategy= (SavingsStrategy & {legacy?:boolean}) | null;
