'use client';
import {useState} from 'react';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Button} from '@/components/ui/button';
import {Checkbox} from '@/components/ui/checkbox';
import {Input} from '@/components/ui/input';
import {dollars,download} from './format';
import type {Plan,ProjectionResult,ProjectionRow,PeopleFlow} from './model-types';
import {annualCSV} from '../../engine/annual-export.mjs';
export function YearDetail({row,real=false,baseYear}:{row:ProjectionRow;real?:boolean;baseYear?:number}){const d=real?row.inflationIndex:1;const group=(title:string,items:[string,number][])=><><h4>{title}</h4><dl className="flow-list">{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd className={label==='Unfunded spending'&&value>1?'negative':''}>{dollars(value/d)}</dd></div>)}</dl></>;
 return <div className="year-detail"><div className="section-head"><div><span className="eyebrow">{row.year} · Age {row.age}</span><h3>Follow the money</h3></div><span className="pill">{real?`${baseYear??'Base-year'} dollars`:'Future dollars'}</span></div>
 {group('Annual income and spending',[['Salary',row.wages],['Other income + Social Security',row.otherIncome+(row.socialSecurity||0)],['Employee pretax 401(k)',-row.employee401k],['Income tax + payroll tax',-(row.ordinaryIncomeTax??row.federalTax)-row.payrollTax],['Early-withdrawal additional tax',-(row.earlyWithdrawalPenalty??0)],['Living, housing + healthcare',-row.spending],['Net healthcare (included above)',row.healthcare?.cost??0],['Home purchase cash',-row.upfront],['Home sale proceeds',row.saleProceeds],['Total outgo incl. tax + purchase',row.totalOutgo],['Withdrawals from accounts',row.peopleFlow?.reduce((v:number,p:PeopleFlow)=>v+p.withdrawals,0)??0],['Cash surplus / true gap after funding',row.cashAfterFunding],['Spending paid from available sources',row.spendingFunded??Math.max(0,row.spending+row.upfront-row.shortfall)],['Unfunded spending',row.unfundedAfterWithdrawals??row.shortfall]])}
 {row.budget&&group('Retirement allowance breakdown', [['Recurring target',row.budget.target],['Housing inside target',row.budget.housing],['Tax inside target',row.budget.includedTax],['Healthcare inside target',row.budget.includedHealth],['Remaining living allowance',row.budget.living],['Calendar expenses + moving outside target',row.budget.outside],['Home purchase cash outside target',row.budget.purchaseUpfront],['Additional tax / healthcare',row.budget.additional],['Protected-cost overrun',row.budget.overrun]])}
 {(row.budget?.overrun??0)>1&&<p className="notice warning">Protected costs exceed the recurring target. Actual costs are shown; the target has not been treated as feasible.</p>}
 {row.hsaReview&&<section><h4>Verified-year HSA funding</h4><p className="small muted">Actual contributions are limited by verified eligible months, shared statutory room and household funding. Direct contributions reduce income tax, but do not exclude FICA. New direct deposits cannot fund their own contribution.</p>{group('HSA contribution review',[['Direct personal contributions',row.hsaReview.direct.reduce((a,b)=>a+b,0)],['Direct Schedule 1 deduction',row.hsaReview.deductible.reduce((a,b)=>a+b,0)],['Payroll exclusion',row.hsaReview.payrollExcluded.reduce((a,b)=>a+b,0)],['Requested saving not affordable',row.hsaReview.fundingShortfall]])}{row.hsaReview.flags.map(flag=><p key={flag} className="notice warning">{flag==='shared_hsa_month_overlap_unverified'?'Spouse eligibility dates are incomplete; the shared contribution room is conservatively capped. Enter exact eligible months.':flag.startsWith('hsa_payroll_without_wages_')?'An HSA payroll election has no wages to fund it. A direct contribution requires a separate verified election.':flag}</p>)}</section>}
 {row.penaltyFallbackUsed&&<p className="notice warning">Funding uses early withdrawals with an additional tax. The paid-spending amount includes these withdrawals; the unfunded amount is what remains after all permitted sources are tried.</p>}
 {group('Account deposits and transfers',[['Roth IRA contributions',row.rothAdded],['Planned taxable deposits',row.brokerAdded],['Surplus + cash swept to taxable',row.investedSurplus],['Employer contributions',row.employer],['Roth conversions (internal transfer)',row.conversion]])}
 {group('Financial asset reconciliation',[['Opening assets',row.openingPortfolio],['Market growth + cash interest',row.growth],['Manual balance adjustments',row.adjustments],['Forfeited employer money',-row.forfeiture],['Closing assets',row.portfolio],['Reconciliation residual',row.reconciliation]])}
 {group('Income used for health planning',[['ACA MAGI',row.magi],['Conversion MAGI target',row.acaLimit],['Room under target',row.acaLimit-row.magi]])}
 <p className="small muted">Sections show cash flows, transfers and asset stocks separately. The healthcare subtotal is included in spending. Conversions and account deposits are transfers, not additional spendable income. Returns already include reinvested distributions. A joint federal tax bill is computed once.</p></div>;
}
const fields=(plan:Plan):[string,string][]=>[['spending','Living + housing override (future dollars)'],['retirementBudget','Retirement allowance override (future dollars)'],['conversion','Roth conversion'],...plan.people.flatMap<[string,string]>(p=>[
 [`${p.id}Salary`,`${p.name} salary`],[`${p.id}401k`,`${p.name} pretax401(k)`],[`${p.id}Roth`,`${p.name} Roth contribution`],[`${p.id}Brokerage`,`${p.name} taxable contribution`],[`${p.id}Income`,`${p.name} other ordinary income`],...['traditional','roth','brokerage','cash'].map<[string,string]>(key=>[`${p.id}_${key}`,`${p.name} ${key} balance adjustment`])])];
export default function Annual({plan,result,onChange,year,onYear,real,onReal}:{plan:Plan;result:ProjectionResult;onChange:(p:Plan)=>void;year:number;onYear:(y:number)=>void;real:boolean;onReal:(v:boolean)=>void}){
 const [visible,setVisible]=useState(['income','deferrals','taxes','spending','outgo','accessible','portfolio','gap']);
 const columns=[{key:'income',label:'Income',value:(r:ProjectionRow)=>r.wages+r.otherIncome+(r.socialSecurity||0)},{key:'deferrals',label:'401(k)',value:(r:ProjectionRow)=>r.employee401k},{key:'taxes',label:'Taxes',value:(r:ProjectionRow)=>r.federalTax+r.payrollTax},{key:'spending',label:'Living + housing + health',value:(r:ProjectionRow)=>r.spending},{key:'outgo',label:'Total outgo',value:(r:ProjectionRow)=>r.totalOutgo},{key:'accessible',label:'Penalty-free assets',value:(r:ProjectionRow)=>r.accessible},{key:'portfolio',label:'Portfolio',value:(r:ProjectionRow)=>r.portfolio},{key:'gap',label:'Gap',value:(r:ProjectionRow)=>r.shortfall}];
 const shown=columns.filter(c=>visible.includes(c.key));
 const [field,setField]=useState('spending'),[amount,setAmount]=useState(''),[error,setError]=useState('');
 const row=result.rows.find((r:ProjectionRow)=>r.year===year)||result.rows[0];
 const d=real?row.inflationIndex:1,unit=real?`${plan.baseYear} dollars`:'Future dollars';
 const opts=[...fields(plan),...plan.expenses.map(e=>[`expense_${e.id}`,`${e.name} (${e.inflate?plan.baseYear+' dollars':'future dollars'})`])];
 function apply(){if(field==='retirementBudget'&&(!plan.retirementBudget?.enabled||year<Math.min(...plan.people.map(p=>p.retireYear)))){setError('Enable the retirement allowance in Your plan → Spending and choose a retired year.');return;}if(field==='retirementBudget'&&plan.overrides[year]?.spending!==undefined){setError('Reset this year’s total-spending override first; it takes precedence over the allowance.');return;}const v=Number(amount);if(amount.trim()===''||!Number.isFinite(v)||v<0){setError('Enter an amount of zero or more.');return;}const p=structuredClone(plan);p.overrides[year]={...p.overrides[year],[field]:v};onChange(p);setAmount('');setError('');}
 function remove(key:string){const p=structuredClone(plan);delete p.overrides[year][key];if(!Object.keys(p.overrides[year]).length)delete p.overrides[year];onChange(p);}
 const csv=()=>download('snooks-annual-projection.csv',annualCSV(plan,result),'text/csv');
 return <div className="stack"><div className="section-head"><div><h2>Annual cash flow</h2><p className="muted">Change one year without rewriting the rest of your plan.</p></div><div className="actions"><div className="segmented"><Button size="sm" variant={real?'default':'ghost'} onClick={()=>onReal(true)}>{plan.baseYear} dollars</Button><Button size="sm" variant={!real?'default':'ghost'} onClick={()=>onReal(false)}>Future dollars</Button></div><Button variant="outline" onClick={csv}>Export CSV</Button></div></div>
 <p className="notice info">{unit}. Inflation changes future-dollar amounts, not a constant purchasing-power budget. The annual ledger and graph share this setting. CSV includes future dollars plus explicitly labeled base-year columns.</p><div className="two-columns"><section className="panel"><h3>Override a single year</h3><div className="field-grid"><label className="field">Year<Input aria-label="Override year" type="number" min={plan.startYear} max={plan.endYear} value={year} onChange={e=>{const y=Number(e.target.value);if(y>=plan.startYear&&y<=plan.endYear)onYear(y);}}/></label><label className="field">What changes?<Select value={field} onValueChange={setField}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{opts.map(([v,t]:string[])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select></label><label className="field">Amount ($)<Input value={amount} onChange={e=>setAmount(e.target.value)} type="number" min="0" placeholder="Inherited unless overridden"/></label></div><Button onClick={apply}>Apply to {year}</Button>{error&&<p role="alert" className="negative">{error}</p>}<p className="small muted">Blank means inherit; zero is a real override. Income and total spending use that year’s dollars. Inflation-linked expense overrides use base-year dollars; noninflating expenses use nominal dollars. A retirement allowance override keeps the tax/health policy. A total-spending override replaces living/housing/moving and adds modeled healthcare and taxes separately; it disables the envelope for that year. Neither override changes with the display toggle. Balance adjustments change assets, not earnings. Other income excludes self-employment tax modeling.</p>
 <div className="override-list">{Object.entries(plan.overrides[year]||{}).map(([k,v])=><div key={k}><span>{opts.find((a:string[])=>a[0]===k)?.[1]||k} <strong>{dollars(Number(v))}</strong></span><Button size="sm" variant="ghost" onClick={()=>remove(k)}>Reset</Button></div>)}</div></section><section className="panel"><YearDetail row={row} real={real} baseYear={plan.baseYear}/></section></div>
 <section className="panel"><h3>Income, savings & withdrawal funding · {year}</h3><Table><TableHeader><TableRow>{['Person','Gross salary','Employee 401(k)','Employee HSA','Payroll tax','Federal tax incl. penalties','Income less all taxes','Roth IRA deposits','Mega-backdoor deposits','Taxable deposits','Withdrawals received','SEPP distributions to cash','Early-withdrawal additional tax','Employer deposits','Employer HSA','Personal spending'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{row.peopleFlow.map((p:PeopleFlow)=><TableRow key={p.id}><TableCell>{p.name}</TableCell>{(['wages','employee401k','employeeHsa','payrollTax','federalTax','earnedIncomeAfterTax','rothAdded','megaBackdoor','taxableDeposits','withdrawals','seppDistribution','penalty','employer','employerHsa','personalSpending'] as const).map(k=><TableCell key={k}>{dollars((p[k]??(k==='earnedIncomeAfterTax'?p.takeHome:0))/d)}</TableCell>)}</TableRow>)}</TableBody></Table><p className="small muted">{unit}. Income less all taxes includes other ordinary income and Social Security but excludes account withdrawals. It can be negative when investment or conversion taxes exceed earned income; this is a funding need. Withdrawals received fund that need and living costs. Federal tax includes the additional early-withdrawal tax shown separately; do not add that column again. SEPP distributions are transferred into cash and can subsequently appear in cash withdrawals received; do not add both columns as new money. The household paid-spending and unfunded amounts above show whether bills were actually covered. {row.joint?'Joint federal tax is allocated by positive modeled income for display; it is legally one household bill.':'Each single tax household is calculated separately.'} Taxable deposits include surplus and cash sweeps, so they are not all new savings. Cash flow is pooled; expense ownership labels do not create separate household accounts.</p></section>
 <section className="panel"><div className="section-head"><h3>Accounts by person · {year}</h3><span className="muted small">{unit} · household cash flow is pooled</span></div><Table><TableHeader><TableRow>{['Person','Gross salary','Traditional','Roth','HSA','Segregated SEPP','Taxable','Cash','Roth basis','Unvested'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{row.accounts.map((a,i)=><TableRow key={a.id}><TableCell>{plan.people[i].name}</TableCell><TableCell>{dollars(row.wagesByPerson[i]/d)}</TableCell>{(['traditional','roth','hsa','sepp','brokerage','cash','rothBasis','unvested'] as const).map(k=><TableCell key={k}>{dollars((a[k]??0)/d)}</TableCell>)}</TableRow>)}</TableBody></Table></section>
 <section className="panel annual-table"><details><summary>Choose ledger columns</summary><div className="ledger-column-options">{columns.map(c=><label key={c.key}><Checkbox checked={visible.includes(c.key)} onCheckedChange={checked=>setVisible(v=>checked?[...v,c.key]:v.filter(key=>key!==c.key))}/>{c.label}</label>)}</div></details><Table><TableHeader><TableRow><TableHead>Year / age</TableHead>{shown.map(c=><TableHead key={c.key}>{c.label}</TableHead>)}</TableRow></TableHeader><TableBody>{result.rows.map((r:ProjectionRow)=>{const rd=real?r.inflationIndex:1;return <TableRow key={r.year} data-state={year===r.year?'selected':undefined}><TableCell><button className="link-button" onClick={()=>onYear(r.year)}>{r.year} / {r.age}{plan.overrides[r.year]?' *':''}</button></TableCell>{shown.map(c=><TableCell key={c.key} className={c.key==='gap'&&r.shortfall>1?'negative':''}>{dollars(c.value(r)/rd)}</TableCell>)}</TableRow>;})}</TableBody></Table><p className="small muted">{unit}. * A year with overrides. Penalty-free balances are before income tax and exclude home equity and restricted funds. Permitted early withdrawals with additional tax are shown separately.</p></section></div>;
}
