'use client';
import {useMemo} from 'react';
import {auditedLegacyWorkspace} from '../../lib/workspace.mjs';
import {sensitivities} from '../../engine/decisions.mjs';
import {Choice} from './PlanEditor';
import {Input} from '@/components/ui/input';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {dollars} from './format';
import type {Plan,Assumption} from './model-types';
type Sensitivity={label:string;note:string;unavailable?:boolean;entryChange?:number;gapYear?:number|null;terminalChange?:number};
export default function Assumptions({plan,onChange}:{plan:Plan;onChange:(p:Plan)=>void}){
 const sensitivity=useMemo<Sensitivity[]>(()=>{try{return sensitivities(plan) as Sensitivity[];}catch{return [];}},[plan]);
 const notes=plan.assumptions,status=(a:Assumption)=>a.status??(a.confirmed?'confirmed':'estimate'),missing:string[]=[];
 for(const p of plan.people){if(!p.birthDate)missing.push(`${p.name}: birth date for coverage and age 59½ access.`);if(!p.rothBasisDocumented)missing.push(`${p.name}: documented remaining regular Roth contribution basis.`);if(p.rothConversionLots?.some((x)=>!x.documented))missing.push(`${p.name}: conversion history has unverified lots.`);}
 if(plan.retirementBudget?.enabled&&plan.retirementBudget.minimumLiving===0)missing.push('Retirement minimum living allowance: zero is a provisional floor; document the essential everyday budget.');
 if(!plan.healthcare?.enabled)missing.push('Healthcare costs are still only whatever your saved living budget includes. Separate planning is off.');
 else for(const p of plan.healthcare.people){if(p.eligibility==='unknown')missing.push(`${plan.people.find((x)=>x.id===p.id)?.name}: ACA eligibility.`);if(p.marketplaceMonthly===0||p.benchmarkMonthly===0)missing.push(`${p.id}: actual Marketplace and benchmark quotes.`);}
 function edit(i:number,key:'status'|'source'|'reviewDate',value:string){const p=structuredClone(plan);p.assumptions[i][key]=value;if(key==='status')p.assumptions[i].confirmed=value==='confirmed';onChange(p);}
 const exact=JSON.stringify(plan)===JSON.stringify(auditedLegacyWorkspace().scenarios[0].plan);
 return <><section className="panel"><h3>Assumption dashboard</h3><p className="muted">Review status describes evidence. It does not change a financial input or prove a forecast.</p><div className="stat-grid">{[['confirmed','Confirmed facts'],['estimate','Estimates'],['missing','Missing information']].map(([key,label])=><div className="stat" key={key}><span>{label}</span><strong>{notes.filter((a)=>status(a)===key).length+(key==='missing'?missing.length:0)}</strong></div>)}</div><details open><summary>Information to resolve next</summary><ul className="small muted">{missing.map(x=><li key={x}>{x}</li>)}</ul><p className="small muted">Also verify brokerage tax basis, income timing, expense coverage and the filing/dependent household. A balance matching today’s value does not confirm its cost basis.</p></details>
 <div className="stack">{notes.map((a,i)=><div key={a.id} className="assumption-entry"><p>{a.text}</p><div className="field-grid"><Choice label="Evidence status" help="Confirmed means you verified the underlying record; estimate is a planning value." value={status(a)} onChange={v=>edit(i,'status',v)} options={ [['confirmed','Confirmed fact'],['estimate','Estimate'],['missing','Missing information']] }/><label className="field">Source / evidence<Input aria-label={`Source for ${a.id}`} value={a.source??''} maxLength={500} onChange={e=>edit(i,'source',e.target.value)} placeholder="Statement date, benefit document, quote…"/></label><label className="field">Review date<Input type="date" aria-label={`Date reviewed for ${a.id}`} value={a.reviewDate??''} onChange={e=>edit(i,'reviewDate',e.target.value)}/></label></div></div>)}</div></section>
 <section className="panel"><h3>Which inputs move the result most?</h3><p className="small muted">One change at a time in the deterministic model, sorted by terminal purchasing-power impact. These are sensitivity checks, not recommended changes or simulation probabilities. Timing changes preserve the same explicit calendar events.</p><Table><TableHeader><TableRow>{['Change tested','Retirement-entry change','First funding gap','Terminal change'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{sensitivity.map((s)=><TableRow key={s.label}><TableCell>{s.label}<p className="small muted">{s.note}</p></TableCell><TableCell>{s.unavailable?'Unavailable':dollars(s.entryChange??0)}</TableCell><TableCell>{s.unavailable?'Unavailable':s.gapYear??'None'}</TableCell><TableCell>{s.unavailable?'Unavailable':dollars(s.terminalChange??0)}</TableCell></TableRow>)}</TableBody></Table><p className="small muted">Money is in {plan.baseYear} dollars. Spending cuts and later retirement can improve a projection while still leaving a bridge problem; use Bridge and Decisions to inspect it.</p></section>
 <section className="panel"><h3>Independent reconciliation of the original saved plan</h3><p>Saved revision 1, October 2, 2026: 18 financial fields across 51 years independently matched to within $0.000107. The checked plan entered 2038 with $2,450,516 nominal, or $1,867,648 in 2026 dollars. Its first access gap was 2056 with $1,403,059 in real assets remaining.</p><p className="small muted">{exact?'This draft matches that checked input snapshot.':'This draft differs from the audited snapshot; the historical independent check does not certify your new inputs.'} The independent reconstruction covers the saved rent/fixed-spending case through 2077, before RMDs, with no Social Security, custom events or healthcare model. New features have separate known-answer and conservation tests.</p><p className="small muted">Earlier chats used real returns, promotions and different opening/timing conventions. Isolating 7% real stock returns before retirement, 5% after and 3% real cash with the same other inputs raises retirement-entry wealth to $2,207,657 real, and moves the first access gap to 2061. The original saved plan used 7% nominal stocks, about 4.39% real before fees. Reconstructed promotions add about $178,831; interpreting $332,500 as investments excluding cash adds about $47,316, but that cash interpretation is unconfirmed. Old chat totals cannot be exactly certified without their formulas, housing cash flows and dollar units. The October 3 corrected baseline uses your requested 7% real stock growth before retirement and 5% real after, preserving cash and bond economic returns. It is a separate scenario; the original audit remains historical.</p><a href="/reconciliation.md" download="Snooks-Reconciliation.md" className="btn btn-secondary">Download full reconciliation</a></section></>;
}
