'use client';
import {useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {planChecks} from './plan-checks.mjs';
import {updateFields,updateTemplate,previewAnnualUpdates,automationBriefing} from './annual-updates.mjs';
import {project} from '../../engine/project.mjs';
import CommitNumberInput from './CommitNumberInput';
import {dollars,download} from './format';
import type {Plan} from './model-types';
type Preview=ReturnType<typeof previewAnnualUpdates>;
export default function AutomationCenter({plan,scenarioId,onCopy,onOpen,canCopy}:{plan:Plan;scenarioId:string;onCopy:(plan:Plan)=>void;onOpen:(page:string)=>void;canCopy:boolean}){
 const template=updateTemplate(plan,scenarioId),fields=updateFields(plan),checks=planChecks(plan);
 const [text,setText]=useState(()=>JSON.stringify(template,null,2)),[year,setYear]=useState(plan.startYear),[field,setField]=useState(fields[0].key),[amount,setAmount]=useState(''),[operation,setOperation]=useState('set'),[error,setError]=useState(''),[yearValid,setYearValid]=useState(true);
 const [preview,setPreview]=useState<{key:string;value:Preview;opening:number|null;terminal:number;previousOpening:number|null;previousTerminal:number}|null>(null);
 const fileInput=useRef<HTMLInputElement|null>(null),key=JSON.stringify([plan,scenarioId,text]),current=preview?.key===key?preview:null;
 function add(){try{if(!yearValid)throw Error('Fix the calendar year before staging an update.');const input=JSON.parse(text);if(!input||input.format!==template.format||!Array.isArray(input.updates))throw Error('Reset the staged list or import a valid annual-update template.');if(input.updates.some((update:{year:number;key:string})=>update.year===year&&update.key===field))throw Error('That year and field are already staged. Remove it before adding a replacement.');if(operation==='set'&&(!amount.trim()||!Number.isFinite(Number(amount))||Number(amount)<0))throw Error('Enter a nonnegative amount; 0 is allowed.');const update={year,key:field,operation,...(operation==='set'?{amount:Number(amount)}:{})};setText(JSON.stringify({...input,updates:[...input.updates,update]},null,2));setError('');setAmount('');}catch(cause){setError(cause instanceof Error?cause.message:'The change could not be staged.');}}
 function review(){try{const value=previewAnnualUpdates(plan,scenarioId,JSON.parse(text)),candidate=project(value.candidate),baseline=project(plan);if(!candidate.terminal||!baseline.terminal)throw Error('The projection did not produce a terminal result.');setPreview({key,value,opening:candidate.retirement?.openingRealPortfolio??null,terminal:candidate.terminal.realPortfolio,previousOpening:baseline.retirement?.openingRealPortfolio??null,previousTerminal:baseline.terminal.realPortfolio});setError('');}catch(cause){setPreview(null);setError(cause instanceof Error?cause.message:'The update file could not be reviewed.');}}
 async function importFile(file:File){try{if(file.size>100000)throw Error('Annual-update files must be under 100 KB.');const parsed=JSON.parse(await file.text());previewAnnualUpdates(plan,scenarioId,parsed);setText(JSON.stringify(parsed,null,2));setError('');}catch(cause){setError(cause instanceof Error?cause.message:'The update file could not be loaded.');}finally{if(fileInput.current)fileInput.current.value='';}}
 const units=(()=>{try{return JSON.parse(text).dollarMode==='nominal'?'each calendar year’s future dollars':`${plan.baseYear} purchasing-power dollars`;}catch{return 'the file’s declared dollar units';}})();
 const staged:( {index:number;year:number;key:string;operation:string;amount?:number})[]=(()=>{try{const updates=JSON.parse(text).updates;if(!Array.isArray(updates))return [];return updates.flatMap((update,index)=>update&&typeof update==='object'&&Number.isInteger(update.year)&&typeof update.key==='string'&&['set','clear'].includes(update.operation)?[{index,year:update.year,key:update.key,operation:update.operation,amount:typeof update.amount==='number'?update.amount:undefined}]:[]);}catch{return [];}})();
 function remove(index:number){try{const input=JSON.parse(text);setText(JSON.stringify({...input,updates:input.updates.filter((_:unknown,i:number)=>i!==index)},null,2));}catch{setError('Reset the staged list or repair the JSON before removing an item.');}}
 return <div className="stack"><section className="panel"><h2>Keep your plan current</h2><p className="muted">Review missing evidence, stage yearly changes, then create a separate scenario. Your original stays available.</p><div className="maintenance-checklist">{checks.length?checks.map(check=><div key={check.id}><div><strong>{check.title}</strong><p className="small muted">{check.detail}</p></div><Button variant="outline" size="sm" onClick={()=>onOpen(check.section)}>Review</Button></div>):<p className="notice info">No checklist gaps detected. This is an input checklist, not independent evidence or a retirement guarantee.</p>}</div></section>
 <section className="panel"><h3>Annual update builder</h3><p className="muted">Change one year without changing later years. Explicit salary overrides can create wages outside regular work dates. Contribution requests still follow available cash and legal limits.</p><div className="field-grid"><CommitNumberInput label="Calendar year" min={plan.startYear} max={plan.endYear} integer value={year} onCommit={setYear} onValidityChange={setYearValid}/><label className="field">Annual field<Select value={field} onValueChange={setField}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{fields.map(field=><SelectItem key={field.key} value={field.key}>{field.label}</SelectItem>)}</SelectContent></Select></label><label className="field">Change<Select value={operation} onValueChange={setOperation}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="set">Set this year’s amount</SelectItem><SelectItem value="clear">Restore the automatic amount</SelectItem></SelectContent></Select></label>{operation==='set'&&<label className="field">Amount in {units}<Input inputMode="decimal" value={amount} onChange={event=>setAmount(event.target.value)} placeholder="e.g. 116700"/></label>}</div><div className="actions"><Button disabled={!yearValid} onClick={add}>Add to staged list</Button><Button variant="outline" onClick={review}>Preview all changes</Button></div>
 <div className="staged-update-list" aria-label="Staged annual updates">{staged.map(update=><div key={update.index}><div><strong>{update.year} · {fields.find(field=>field.key===update.key)?.label??update.key}</strong><p className="small muted">{update.operation==='clear'?'Restore automatic amount':`${update.amount===undefined?'Amount missing':dollars(update.amount)} in ${units}`}</p></div><Button size="sm" variant="ghost" onClick={()=>remove(update.index)} aria-label={`Remove staged update for ${update.year} ${update.key}`}>Remove</Button></div>)}</div>
 <details><summary>Reusable files for automated updates</summary><p className="small muted">Download a template for an assistant or script to fill, then import its result here. The scenario ID, dollar year and allowed fields are validated before anything changes. The assistant briefing includes your active plan and review checklist; keep that financial export private. No bank connection or background schedule is enabled.</p><div className="actions"><Button variant="outline" onClick={()=>download('snooks-assistant-briefing.json',JSON.stringify(automationBriefing(plan,scenarioId,new Date().toISOString()),null,2))}>Export assistant briefing</Button><Button variant="outline" onClick={()=>download('snooks-annual-update-template.json',JSON.stringify(template,null,2))}>Download template</Button><Button variant="outline" onClick={()=>download('snooks-staged-updates.json',text)}>Export staged file</Button><Button variant="outline" onClick={()=>fileInput.current?.click()}>Import update file</Button><Button variant="ghost" onClick={()=>{setText(JSON.stringify(template,null,2));setError('');}}>Reset staged list</Button><input hidden type="file" ref={fileInput} accept=".json,application/json" onChange={event=>{const file=event.target.files?.[0];if(file)void importFile(file);}}/></div><label className="field">Staged update JSON<Textarea value={text} maxLength={100000} rows={10} spellCheck={false} onChange={event=>setText(event.target.value)}/></label><p className="small muted">Fields: {fields.map(field=>field.key).join(', ')}. The importer preserves each field’s units: indexed expense overrides stay in base-year dollars; other overrides use nominal dollars. Inflation stress paths follow those native rules, so a nominal quote for an indexed expense is exact only on the baseline inflation path. A clear operation removes an override; it does not mean zero. This tool cannot alter balances, tax basis, permissions or confirmed facts.</p></details>
 {error&&<p className="notice error" role="alert">{error}</p>}
 {current&&<section className="update-preview"><h4>Review before creating a copy</h4><p className="small muted">Your active draft → reviewed copy · {plan.baseYear} dollars</p><dl className="flow-list"><div><dt>Entering retirement</dt><dd>{current.previousOpening===null?'Outside forecast':dollars(current.previousOpening)} → {current.opening===null?'Outside forecast':dollars(current.opening)}</dd></div><div><dt>Financial assets at forecast end</dt><dd>{dollars(current.previousTerminal)} → {dollars(current.terminal)}</dd></div></dl><Table><TableHeader><TableRow>{['Year','Field','Existing override','Proposed override'].map(label=><TableHead key={label}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{current.value.changes.map(change=><TableRow key={`${change.year}:${change.key}`}><TableCell>{change.year}</TableCell><TableCell>{change.label}</TableCell><TableCell>{change.previous===null?'Automatic':dollars(change.previous)}</TableCell><TableCell>{change.next===null?'Automatic':dollars(change.next)}</TableCell></TableRow>)}</TableBody></Table><p className="small muted">Override columns are each calendar year’s nominal dollars. This deterministic preview is not a new market test. Run identical market paths on the copy before relying on it.</p>{current.value.warnings.length>0&&<div className="notice warning"><ul>{current.value.warnings.map(warning=><li key={warning}>{warning}</li>)}</ul></div>}<Button disabled={!canCopy} onClick={()=>onCopy(current.value.candidate)}>Create reviewed scenario copy</Button><p className="small muted">The copy becomes an unsaved draft. Save plan, or enable autosave, to keep it. Existing overrides not listed above remain intact.</p></section>}
 </section><section className="panel"><h3>Automation boundaries</h3><p>Autosave keeps valid edits in your private workspace and stops on a save failure or revision conflict. Undo and redo work during this session. Export a backup before major changes.</p><p className="small muted">Account synchronization, recurring background runs and refreshes of tax law are not enabled. Annual-update files are reviewed inputs, not verified financial records. Scheduled automation should create reviewable proposals rather than silently change returns, balances or eligibility.</p></section></div>;
}
