'use client';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Button} from '@/components/ui/button';
import type {Plan,ProjectionResult,ProjectionRow,AccessBreakdown} from './model-types';
import {accessYear} from '../../engine/access.mjs';
import {dollars} from './format';
export default function Bridge({plan,result,year,onYear,onEdit}:{plan:Plan;result:ProjectionResult;year:number;onYear:(y:number)=>void;onEdit:()=>void}){
 const row=result.rows.find((r:ProjectionRow)=>r.year===year)??result.rows[0],first=Math.min(...plan.people.map((p)=>p.retireYear)),end=Math.max(...plan.people.map(accessYear))+5;
 return <div className="stack"><section className="panel"><div className="section-head"><div><h2>Your retirement bridge</h2><p className="muted">Separate money available to spend from balances still behind access rules.</p></div><Button variant="outline" onClick={onEdit}>Edit basis &amp; history</Button></div><p className="notice info">Roth contribution basis means documented contributions remaining after prior withdrawals. It is independent of market value and may exceed it after losses. A missing history is not inferred from account value. The accessible balances below show penalty-free access. Early withdrawals with additional tax are shown separately when enabled and the account permits distributions. Home equity is excluded.</p>
 <div className="stat-grid">{plan.people.map((p)=><div className="stat" key={p.id}><span>{p.name}</span><strong>{accessYear(p)}</strong><p>First modeled full year of age 59½ access · {p.birthDate?'date-based':'approximate; birth date missing'}</p><p>{p.rothBasisDocumented?'Contribution basis marked documented':'Contribution basis unverified'} · Roth qualification year {p.penaltyExceptions?.rothDisabilityVerified===true?p.rothOpenYear+5:Math.max(accessYear(p),p.rothOpenYear+5)}</p></div>)}</div></section>
 <section className="panel"><h3>Bridge timeline · {plan.baseYear} dollars</h3><Table><TableHeader><TableRow>{['Year','Cash + taxable','Roth contribution basis','Penalty-free conversion principal','Eligible traditional','Penalty-free total','Withdrawals','Early-withdrawal additional tax','Funding gap'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{result.rows.filter((r:ProjectionRow)=>r.year>=first&&r.year<=end).map((r:ProjectionRow)=>{const a=r.accessByPerson,d=r.inflationIndex,sum=(key:'cash'|'taxable'|'basis'|'seasoned'|'traditional')=>a.reduce((v:number,x:AccessBreakdown)=>v+x[key],0)/d;return <TableRow key={r.year} data-state={r.year===year?'selected':undefined}><TableCell><button className="link-button" onClick={()=>onYear(r.year)}>{r.year}</button></TableCell><TableCell>{dollars(sum('cash')+sum('taxable'))}</TableCell><TableCell>{dollars(sum('basis'))}</TableCell><TableCell>{dollars(sum('seasoned')+a.reduce((v:number,x:AccessBreakdown)=>v+Number(x.unseasonedPenaltyFree??0),0)/d)}</TableCell><TableCell>{dollars(sum('traditional'))}</TableCell><TableCell>{dollars(r.accessible/d)}</TableCell><TableCell>{dollars(r.peopleFlow.reduce((v:number,p)=>v+p.withdrawals,0)/d)}</TableCell><TableCell>{dollars((r.earlyWithdrawalPenalty??0)/d)}</TableCell><TableCell className={r.shortfall>1?'negative':''}>{dollars(r.shortfall/d)}</TableCell></TableRow>;})}</TableBody></Table><p className="small muted">Year-end balances after withdrawals. A zero penalty-free accessible balance does not itself mean a funding failure: permitted early withdrawals can still pay costs with taxes and penalties. Penalty-free conversion principal includes untaxed portions of unseasoned lots only when IRS ordering permits access. Penalty-free total is before income tax and can include taxable Roth earnings, age65 HSA funds and exempt traditional distributions; components then need not sum to the displayed total. Select a year to inspect remaining conversion lots below.</p></section>
 {row.accounts.some(a=>a.pretaxSources?.length)&&<section className="panel"><h3>Tracked traditional sources at {row.year}</h3>{row.accounts.map((a,i)=><div key={a.id}><h4>{plan.people[i].name}</h4><dl className="flow-list">{(a.pretaxSources??[]).map(source=><div key={source.id}><dt>{source.id} · {source.kind==='traditional_ira'?'IRA':'Former employer'} · {source.verified?'Access confirmed':'Access unconfirmed'}</dt><dd>{dollars(source.balance/row.inflationIndex)}</dd></div>)}<div><dt>Untracked vested remainder</dt><dd>{dollars(Math.max(0,a.traditional-a.unvested-(a.pretaxSources??[]).reduce((v,s)=>v+s.balance,0))/row.inflationIndex)}</dd></div></dl></div>)}<p className="small muted">Amounts are in {plan.baseYear} purchasing power and are portions of traditional assets, never additional assets. Current workplace contributions enter the remainder. Conversions and withdrawals reduce the source actually used.</p></section>}
 <section className="panel"><h3>Conversion lots remaining at the end of {row.year}</h3>{row.accounts.map((a,i)=><div key={a.id}><h4>{plan.people[i].name}</h4>{a.lots.length?<Table><TableHeader><TableRow>{['Conversion tax year','Remaining principal (future $)','Taxable conversion principal (future $)','Seasoning date','Status','Source'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{a.lots.map((lot,index)=><TableRow key={index}><TableCell>{lot.year}</TableCell><TableCell>{dollars(lot.amount)}</TableCell><TableCell>{dollars(lot.taxableAmount??lot.amount)}</TableCell><TableCell>January 1, {lot.year+5}</TableCell><TableCell>{row.year>=accessYear(plan.people[i])?'Age exception available':row.year>=lot.year+5?'Seasoned':'Waiting'}</TableCell><TableCell>{lot.documented?'Documented opening history':'Projected conversion'}</TableCell></TableRow>)}</TableBody></Table>:<p className="small muted">No conversion lots entered or projected by this year.</p>}</div>)}<p className="small muted">The engine withdraws regular contributions first, then conversion principal by conversion year, then earnings. Within a conversion year, taxable converted principal is used before nontaxable principal. Early taxable conversion principal can incur recapture tax; nonqualified earnings can incur income tax and an additional tax. Enter remaining taxable and total principal accurately; unknown taxable principal is conservatively treated as fully taxable. A five-tax-year seasoning date is not the same as the Roth account qualification clock.</p></section></div>;
}
