'use client';
import {useMemo} from 'react';
import {Button} from '@/components/ui/button';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {failureDiagnosis,projectionComparison,returnSummary} from '../../engine/diagnostics.mjs';
import {dollars,compact,percent} from './format';
import type {Plan,ProjectionResult} from './model-types';

export default function Diagnostics({plan,result,onInspect,onReview,onCompare,canCopy}:{plan:Plan;result:ProjectionResult;onInspect:(year:number)=>void;onReview:()=>void;onCompare:()=>void;canCopy:boolean}){
 const comparison=useMemo(()=>projectionComparison(plan),[plan]);
 const penaltyYear=result.rows.find((r)=>r.penaltyFallbackUsed||r.earlyWithdrawalPenalty>1);
 const failure=failureDiagnosis(result),working=returnSummary(plan),retired=returnSummary(plan,true);
 const zeroBasis=plan.people.filter((p)=>p.roth>0&&p.rothBasis===0).map((p)=>p.name);
 return <section className="panel diagnostics"><div className="section-head"><div><h2>Why this result?</h2><p className="muted">See the assumptions behind the warning before changing the plan.</p></div><Button variant="outline" onClick={onReview}>Review inputs</Button></div>
 {failure?<><h3>{failure.type==='access-gap'?`Access gap in ${failure.row.year}`:failure.type==='depletion'?`Portfolio depleted in ${failure.row.year}`:`Funding shortfall in ${failure.row.year}`}</h3><p>{failure.type==='access-gap'?'Money remains, but the modeled withdrawal rules cannot make enough of it available to pay that year’s costs.':failure.type==='depletion'?'The modeled financial accounts are exhausted and cannot fund all costs.':'Some wealth remains, but both account access and the amount of wealth need review.'} Home equity is separate.</p><dl className="diagnostic-metrics"><div><dt>Unfunded costs</dt><dd>{dollars(failure.realGap)}</dd></div><div><dt>Financial assets remaining</dt><dd>{compact(failure.row.realPortfolio)}</dd></div><div><dt>Accessible at year end</dt><dd>{dollars(failure.realAccessible)}</dd></div></dl><Button variant="outline" onClick={()=>onInspect(failure.row.year)}>Inspect {failure.row.year}</Button><p className="small muted">Amounts are in {plan.baseYear} dollars. A later recovery does not erase an earlier funding gap. Access follows the current model’s age-59½ full-year rule, Roth basis, conversion timing, permitted early distributions and chosen withdrawal policy; it does not test every possible legal withdrawal strategy.</p></>:<p className="notice info">No unfunded year in the deterministic baseline. This is a fixed-return projection, not a Monte Carlo passing percentage.</p>}
 {penaltyYear&&<p className="notice warning">Funding uses penalty-bearing early withdrawals beginning in {penaltyYear.year}. They are included in the tax bill and withdrawals; evaluate the conversion ladder and alternatives before treating the bridge as efficient.</p>}
 <div className="two-columns diagnostic-returns"><div><h3>During accumulation</h3><p>Stocks: <strong>{percent(working.stock)} {working.unit}</strong> = {percent(working.stockReal)} real. Inflation: {percent(working.inflation)}.</p><p className="small muted">Real returns measure purchasing power. 7% nominal with 2.5% inflation is about 4.39% real; 7% real is about 9.68% nominal.</p></div><div><h3>During retirement</h3><p>Stocks: <strong>{percent(retired.stock)} {retired.unit}</strong>. Allocation: {percent(retired.stockWeight)} stocks.</p><p className="small muted">Weighted stock/bond return after fees: {percent(retired.portfolioReal)} real, before household taxes. Bonds, fees, cash and taxes make the portfolio differ from the stock-only assumption.</p></div></div>
 <p className="small muted">Monte Carlo stocks use {plan.stockReturnMean==='geometric'?'long-run compounded growth (geometric)':'average single-year returns (arithmetic)'}. Historical and bootstrap methods replay observed returns rather than your forecast growth rate. With variable inflation, real-return inputs track each simulated inflation rate; cash and bond unit conversion preserves economics at the configured inflation assumption.</p><h3>Compare with the earlier FIRE discussion</h3><Table><TableHeader><TableRow><TableHead>Assumptions</TableHead><TableHead>Entering retirement</TableHead><TableHead>First shortfall</TableHead></TableRow></TableHeader><TableBody>{comparison.map(({label,entry,failure})=><TableRow key={label}><TableCell>{label}</TableCell><TableCell>{entry?compact(entry.realPortfolio):'Outside horizon'}</TableCell><TableCell>{failure?`${failure.row.year} · ${failure.type==='access-gap'?'access gap':failure.type==='depletion'?'depleted':'funding gap'}`:'None in horizon'}</TableCell></TableRow>)}</TableBody></Table>
 <p className="small muted">The comparison changes stock returns to 7% real before retirement and 5% real after, and cash to 3% real. It preserves your current accounts, dates, spending, allocation and bond assumptions. Earlier chat estimates used other inputs too; neither projection proves those estimates correct.</p><Button disabled={!canCopy} variant="outline" onClick={onCompare}>Create comparison scenario</Button>
 {zeroBasis.length>0&&<p className="notice warning">Roth contribution basis is zero for {zeroBasis.join(' and ')}. That does not mean it actually is zero. Enter your documented contribution history to model eligible early withdrawals accurately; do not enter the entire account value as basis.</p>}
 <p className="small muted">Retirement means the first full year without salary for that person. Balances entering retirement are measured before that year’s returns, withdrawals and overrides. Forecast starts in {plan.startYear}; first retirement is {Math.min(...plan.people.map((p)=>p.retireYear))}; horizon ends in {plan.endYear}.</p>
 </section>;
}
