'use client';
import {healthDefaults,HEALTH_RULES_DATE,HEALTH_SOURCES} from '../../engine/healthcare.mjs';
import {NumberField,Choice,Toggle,Advanced} from './PlanEditor';
import {Button} from '@/components/ui/button';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {dollars} from './format';
import type {Plan,ProjectionResult,HealthConfig,HealthPerson,CoverageKind} from './model-types';
import {writePath} from './edit-path';
export default function Healthcare({plan,result,onChange,year,onYear}:{plan:Plan;result:ProjectionResult|null;onChange:(p:Plan)=>void;year:number;onYear:(y:number)=>void}){
 const health:HealthConfig=plan.healthcare??healthDefaults(plan),row=result?.rows.find((r)=>r.year===year)??result?.rows[0]??{year,magi:0,healthcare:{people:[],cost:0,flags:['Correct the invalid inputs above before using this ledger.']}};
 function edit(path:(string|number)[],value:unknown){const p=structuredClone(plan);p.healthcare=structuredClone(health);writePath(p.healthcare,path,value);onChange(p);}
 const num=(i:number,k:Exclude<keyof HealthPerson,'id'|'parentType'|'eligibility'|'coverageOverrides'>,label:string,help:string)=> <NumberField label={label} help={help} value={health.people[i][k]} onChange={v=>edit(['people',i,k],v)} min={0}/>;
 const lookback=health.lookback?.[year-2]??{magi:0,byPerson:[0,0],joint:year-2>=plan.jointYear};
 return <div className="stack"><section className="panel"><h2>Coverage through every life stage</h2><p className="muted">Rules checked {HEALTH_RULES_DATE}. Quotes, enrollment and eligibility remain your inputs.</p><Toggle label="Include separate healthcare costs in the projection" help="Off preserves your existing budgets. On adds net premiums and out-of-pocket costs to spending, with taxes and ACA MAGI solved together." checked={health.enabled} onChange={v=>edit(['enabled'],v)}/><details><summary>Avoid counting healthcare twice</summary><p className="small muted">If a living budget already contains healthcare, split out that portion as an expense category, then select it below to replace it. Do not exclude your entire living budget.</p>{plan.expenses.map((e)=><Toggle key={e.id} label={`Replace: ${e.name}`} help={`Removes this whole category when healthcare is on: ${dollars(e.annual)} / year.`} checked={health.replacedExpenseIds.includes(e.id)} onChange={v=>edit(['replacedExpenseIds'],v?[...health.replacedExpenseIds,e.id]:health.replacedExpenseIds.filter((id:string)=>id!==e.id))}/>)}</details><div className="field-grid"><NumberField label="Premium / out-of-pocket growth" help="Quoted amounts below use base-year dollars." value={health.premiumGrowth} onChange={v=>edit(['premiumGrowth'],v)} percent min={0} max={1}/><NumberField label="Future poverty guideline growth" help="Uses published 2026/2027 FPL, then explicit indexation." value={health.fplGrowth} onChange={v=>edit(['fplGrowth'],v)} percent min={0} max={1}/><NumberField label="Future Medicare indexation" help="2026 premiums and IRMAA thresholds grow at this assumed rate." value={health.medicareGrowth} onChange={v=>edit(['medicareGrowth'],v)} percent min={0} max={1}/></div></section>
 {plan.people.map((person,i)=><section className="panel" key={person.id}><h3>{person.name}</h3><p className="small muted">Automatic schedule: parent coverage before 26, employer coverage during working years, Marketplace outside the working window through 65, Medicare at 65. During a career break employer benefits remain an unverified assumption; use coverage-month overrides. Confirm actual enrollment. Birth date in Your plan improves transition timing; employment plan terms can differ.</p><div className="field-grid"><Choice label="Parent's plan type" help="Employer dependent coverage normally ends at 26; parent Marketplace coverage can continue through December." value={health.people[i].parentType} onChange={v=>edit(['people',i,'parentType'],v)} options={ [['employer','Employer plan'],['marketplace','Marketplace plan']] }/>{num(i,'parentAnnual','Annual household cost of parent coverage','Additional cost paid by your household, not the parent’s entire premium.')}{num(i,'employerAnnual','Annual employee premium','After-tax cash cost estimate. Section 125 payroll deductions are not modeled.')}{num(i,'marketplaceMonthly','Monthly Marketplace premium','Actual age/location-specific quote, before subsidy.')}{num(i,'benchmarkMonthly','Monthly benchmark Silver premium','SLCSP quote used to estimate premium tax credit.')}{num(i,'outOfPocketAnnual','Annual out-of-pocket budget','Deductibles, copays and uncovered costs; do not enter a plan limit as expected spending.')}<Choice label="ACA credit eligibility" help="Eligible means you verified Marketplace enrollment, dependency/filing rules and absence of disqualifying affordable minimum-value employer coverage. Unknown assumes no credit." value={health.people[i].eligibility} onChange={v=>edit(['people',i,'eligibility'],v)} options={ [['unknown','Not verified'],['eligible','Verified eligible'],['ineligible','Ineligible']] }/></div>
 <Advanced title="Medicare premiums & gaps"><div className="field-grid">{num(i,'partAMonthly','Monthly Part A premium','Zero assumes premium-free eligibility; verify work credits.')}{num(i,'partDMonthly','Monthly drug-plan premium','Part D plan quote, excluding the income surcharge.')}{num(i,'supplementMonthly','Monthly supplement / Advantage premium','Choose your coverage path; avoid overlapping Medigap and Advantage quotes.')}</div><p className="small muted">2026 Part B is $202.90/month before IRMAA, with a $283 annual deductible. Part A’s $1,736 inpatient deductible is per benefit period. These deductibles are reference amounts, not automatically added; Original Medicare has no annual out-of-pocket cap. Include expected exposure in the annual out-of-pocket budget.</p></Advanced>
 <Advanced title="Edit coverage months in a single year"><NumberField label="Coverage year" help="This selector also updates the ledger below." value={year} onChange={onYear} min={plan.startYear} max={plan.endYear} integer/>{(()=>{const existing=health.people[i].coverageOverrides.find((x)=>x.year===year);return <><Button variant="outline" onClick={()=>{if(!existing)edit(['people',i,'coverageOverrides'],[...health.people[i].coverageOverrides,{year,months:{parent:0,employer:0,marketplace:12,medicare:0,uninsured:0}}]);}} disabled={!!existing}>Customize {year}</Button>{existing&&<><div className="field-grid">{(['parent','employer','marketplace','medicare','uninsured'] as CoverageKind[]).map(kind=><NumberField key={kind} label={`${kind} months`} help="Counts must total 12 for a full year; ordered parent, employer, Marketplace, Medicare, uninsured." value={existing.months[kind]??0} min={0} max={12} integer onChange={v=>edit(['people',i,'coverageOverrides'],health.people[i].coverageOverrides.map((x)=>x.year===year?{...x,months:{...x.months,[kind]:v}}:x))}/>)}</div><Button variant="ghost" onClick={()=>edit(['people',i,'coverageOverrides'],health.people[i].coverageOverrides.filter((x)=>x.year!==year))}>Restore automatic coverage</Button></>}</>;})()}</Advanced></section>)}
 <section className="panel"><h3>{row.year} healthcare ledger</h3><NumberField label="Inspect year" help="Costs below reflect this scenario, including its withdrawals and conversions." value={year} onChange={onYear} integer min={plan.startYear} max={plan.endYear}/>{!health.enabled?<p className="notice info">Separate healthcare modeling is off. Add verified quotes before enabling it; zero inputs can understate costs.</p>:<><Table><TableHeader><TableRow>{['Person','Coverage months','Net cost (future $)','ACA credit','IRMAA tier'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{row.healthcare.people.map((p)=><TableRow key={p.id}><TableCell>{p.name}</TableCell><TableCell>{Object.entries(p.months).filter(([,v])=>Number(v)>0).map(([k,v])=>`${k}: ${v}`).join(', ')}</TableCell><TableCell>{dollars(p.cost)}</TableCell><TableCell>{dollars(p.credit)}</TableCell><TableCell>{p.irmaaTier===null?'—':p.irmaaTier}</TableCell></TableRow>)}</TableBody></Table><p>Total net cost: <strong>{dollars(row.healthcare.cost)}</strong> · ACA household MAGI {dollars(row.magi)}</p><ul className="small muted">{row.healthcare.flags.map((flag:string)=><li key={flag}>{flag}</li>)}</ul></>}
 <Advanced title={`Supply missing ${year-2} IRMAA lookback income`}><p className="small muted">IRMAA normally uses income from two years earlier. Forecast history takes priority unless you enter a manual override. MAGI here is AGI plus tax-exempt interest, not ACA MAGI. Manual values are nominal dollars from the lookback year.</p><div className="field-grid"><NumberField label="Household lookback MAGI" help="Used for joint filing in the lookback year." value={lookback.magi} min={0} onChange={v=>edit(['lookback'],{...(health.lookback??{}),[year-2]:{...lookback,magi:v}})}/>{plan.people.map((p,i)=><NumberField key={p.id} label={`${p.name} lookback MAGI`} help="Used for separate single tax households." value={lookback.byPerson[i]} min={0} onChange={v=>{const a=[...lookback.byPerson];a[i]=v;edit(['lookback'],{...(health.lookback??{}),[year-2]:{...lookback,byPerson:a}});}}/>)}</div><Toggle label="Joint filing in lookback year" help="Thresholds follow filing status two years before the premium year." checked={lookback.joint} onChange={v=>edit(['lookback'],{...(health.lookback??{}),[year-2]:{...lookback,joint:v}})}/><Button variant="ghost" onClick={()=>{const next={...(health.lookback??{})};delete next[year-2];edit(['lookback'],next);}}>Use forecast lookback</Button></Advanced></section>
 <section className="panel"><h3>Dated rules and assumptions</h3><p className="small muted">2026 and 2027 ACA percentages are published; after 2027 this model freezes the 2027 percentage policy and indexes poverty guidelines. Credits stop above 400% FPL under that policy; below 100% no credit is assumed, so review Medicaid and any legal exceptions separately. Costs use continuous annual interpolation, not exact Form 8962 rounding. Joint filing uses a two-person tax family; before joint filing the two single households are separate. Dependents, Medicaid eligibility, employer affordability determinations and monthly tax reconciliation require outside verification. Annual net costs already reflect credits; advance-credit repayment is not added again. Tax-exempt interest and foreign excluded income are unsupported. Medicare assumes timely enrollment; penalties and SSA life-event appeals are excluded.</p><ul>{HEALTH_SOURCES.map(([name,url]:string[])=><li key={url}><a href={url} target="_blank" rel="noreferrer">{name}</a></li>)}</ul></section>
 </div>;
}
