'use client';
import {useCallback,useEffect,useMemo,useReducer,useRef,useState,useSyncExternalStore} from 'react';
import {Tabs,TabsContent} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Cloud,Download,Upload,Layers,ShieldCheck,AlertTriangle,Save,BarChart3,HelpCircle,X} from 'lucide-react';
import {project} from '../../engine/project.mjs';
import {validate} from '../../engine/plan.mjs';
import {workspaceErrors} from '../../lib/workspace.mjs';
import DecisionDashboard from './DecisionDashboard';
import WithdrawalComparison from './WithdrawalComparison';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription,SheetClose} from '@/components/ui/sheet';
import PlanEditor from './PlanEditor';
import Bridge from './Bridge';
import Healthcare from './Healthcare';
import Decisions from './Decisions';
import Assumptions from './Assumptions';
import FinanceSnapshot from './FinanceSnapshot';
import ScenarioReconciliation from './ScenarioReconciliation';
import AutomationCenter from './AutomationCenter';
import {createSaveSession} from './save-session.mjs';
import {createLoadGuard} from './load-guard.mjs';
import {workspaceHistory,initialHistory} from './workspace-history.mjs';
import {planChecks} from './plan-checks.mjs';
import {decisionPlan} from '../../engine/decisions.mjs';
import {earlierReturnPlan} from '../../engine/diagnostics.mjs';
import {createBrowserWorkspace} from './browser-workspace.mjs';
import TaxYear from './TaxYear';
import StressCases from './StressCases';
import Annual from './Annual';
import StressTests from './StressTests';
import ProjectionChart from '../charts/ProjectionChart';
import {compact,dollars,download} from './format';

import type {Plan,ProjectionResult} from './model-types';
type Workspace={version:number;activeId:string;scenarios:{id:string;plan:Plan}[];notes:string};
type WorkspaceResponse={workspace:Workspace;revision:number;updatedAt:string|null};
function validWorkspace(input:unknown):input is Workspace {return workspaceErrors(input).length===0;}
function responseRevision(input:unknown):number {
 if(input===null||typeof input!=='object'||!('revision' in input)||typeof input.revision!=='number'||!Number.isInteger(input.revision)||input.revision<0)throw Error('Invalid workspace revision response.');
 return input.revision;
}
function workspaceResponse(input:unknown):WorkspaceResponse {
 if(input===null||typeof input!=='object')throw Error('Invalid workspace response.');
 const body=input as Record<string,unknown>;
 if(!validWorkspace(body.workspace)||!Number.isInteger(body.revision))throw Error('Invalid workspace response.');
 return {workspace:body.workspace,revision:body.revision as number,updatedAt:typeof body.updatedAt==='string'&&Number.isFinite(Date.parse(body.updatedAt))?body.updatedAt:null};
}
function responseError(input:unknown,fallback:string):string {if(input&&typeof input==='object'&&'error' in input&&typeof input.error==='string')return input.error;return fallback;}
type ModelContext={registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>Promise<unknown>|unknown};
const sections=[['overview','Overview'],['automation','Plan upkeep & automation'],['tax','2026 taxes'],['plan','Your plan'],['annual','Year by year'],['bridge','Bridge'],['withdrawals','Withdrawal policies'],['health','Healthcare'],['decisions','Decisions'],['scenarios','Scenarios'],['stress','Stress tests'],['review','Review']];
const limits=[['Federal taxes','2026 ordinary brackets, preferential gains, NIIT, payroll tax and benefit taxation. Future parameters follow your inflation assumption. FL/TN state income tax is zero.'],['Early retirement access','Cash, taxable accounts, Roth contribution basis and seasoned conversions. Full birth dates use the first full year after age 59½; birth-year-only timing remains an approximation. Permitted early distributions can fund shortfalls with explicit taxes and penalties. SEPP and rule-of-55 exceptions require separate eligibility review.'],['Healthcare','Optional dated ACA/Medicare cost model including two-year IRMAA lookback, coverage months and explicit quotes. Annual estimates; eligibility, enrollment, exact Form 8962, payroll premium deductions and future law require review.'],['Market testing','Monte Carlo, five-year block resampling, and complete 1928–2025 return windows. Choose fixed inflation, variable Monte Carlo inflation, or matched annual historical CPI. Tax law and housing price/rent growth remain planning assumptions.'],['Tax-advantaged savings','Reviewed HSA elections with exact-year eligibility/months and optional direct household funding; clean-IRA backdoor Roth and provider-permitted mega-backdoor routes. New contributions are bounded by legal limits and available funding. Future statutory limits are forecast estimates.'],['Other tax rules','The separate 2026 sandbox includes self-employment tax and QBI. Forward other income is ordinary; itemization, general credits, loss carryforwards and lot optimization are not included.'],['Records & accounts','Import a private JSON workspace or enter your figures. No automatic ChatGPT-memory refresh or live bank synchronization.']];
export default function Planner(){
 const [page,setPage]=useState('overview'),[year,setYear]=useState(2038),[real,setReal]=useState(true),[loading,setLoading]=useState(true),[error,setError]=useState(''),[auth,setAuth]=useState(false),[newName,setNewName]=useState(''),[createOpen,setCreateOpen]=useState(false),[deleteOpen,setDeleteOpen]=useState(false),[reloadOpen,setReloadOpen]=useState(false),[imported,setImported]=useState<Workspace|null>(null),[compareId,setCompareId]=useState(''),[helpOpen,setHelpOpen]=useState(false);
 const [history,dispatchHistory]=useReducer(workspaceHistory,undefined,initialHistory);
 const workspace=history.present as Workspace|null;
 const [store]=useState(()=>createBrowserWorkspace(window.localStorage,{locks:navigator.locks}));
 const [saveSession]=useState(()=>createSaveSession({persist:async(snapshot:string,expectedRevision:number)=>store.save(JSON.parse(snapshot),expectedRevision)}));
 const [loadGuard]=useState(()=>createLoadGuard({getSaveState:saveSession.getSnapshot}));
 const setWorkspace=useCallback((value:Workspace|null|((workspace:Workspace|null)=>Workspace|null))=>{loadGuard.markEdited();dispatchHistory({type:'edit',value});},[loadGuard]);
 const saveState=useSyncExternalStore(saveSession.subscribe,saveSession.getSnapshot,saveSession.getSnapshot),saved=saveState.snapshot,saving=saveState.phase==='saving';
 const [autoSave,setAutoSave]=useState(()=>{if(typeof window==='undefined')return false;try{return localStorage.getItem('snooks.autosave.enabled')==='true';}catch{return false;}});
 function toggleAutoSave(enabled:boolean){setAutoSave(enabled);try{localStorage.setItem('snooks.autosave.enabled',String(enabled));}catch{/* This preference lasts for the current session only. */}}
 const fileInput=useRef<HTMLInputElement|null>(null); const workerPlan=workspace?.scenarios.find(s=>s.id===workspace.activeId)?.plan;
 const serialized=workspace?JSON.stringify(workspace):'';const dirty=!!workspace&&saved!==serialized;
 const plan=workerPlan;
 const errors=useMemo(()=>{if(!plan)return [];try{return validate(plan);}catch{return ['Invalid plan structure.'];}},[plan]);
 const projection=useMemo<{result:ProjectionResult|null;error:string}>(()=>{if(!plan||errors.length)return {result:null,error:''};try{return {result:project(plan),error:''};}catch(cause){return {result:null,error:cause instanceof Error?cause.message:'The calculation could not finish.'};}},[plan,errors]);
 const result=projection.result;
 const safeYear=plan?Math.min(plan.endYear,Math.max(plan.startYear,year)):year;
 const comparison=workspace?.scenarios.find(s=>s.id===compareId);
 const compareResult=useMemo(()=>{if(!comparison)return null;try{return project(comparison.plan);}catch{return null;}},[comparison]);
 const load=useCallback(async(signal?:AbortSignal)=>{const ticket=loadGuard.begin();try{const data=workspaceResponse(store.read());if(!loadGuard.isCurrent(ticket,signal))return;loadGuard.assertUnchanged(ticket,signal);setAuth(false);setError('');saveSession.reset({revision:data.revision,snapshot:JSON.stringify(data.workspace),updatedAt:data.updatedAt});loadGuard.markEdited();dispatchHistory({type:'reset',value:data.workspace});}catch(e){if(loadGuard.isCurrent(ticket,signal))setError((e as Error).message);}finally{if(loadGuard.isCurrent(ticket,signal))setLoading(false);}},[saveSession,loadGuard,store]);
 useEffect(()=>{const request=new AbortController();void Promise.resolve().then(()=>{if(!request.signal.aborted)return load(request.signal);});return()=>request.abort();},[load]);
 useEffect(()=>{if(!dirty)return;const prevent=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent);},[dirty]);
 const latest=useRef({workspace,result});useEffect(()=>{latest.current={workspace,result};},[workspace,result]);
 useEffect(()=>{const ctx=(document as Document & {modelContext?:ModelContext}).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(ctx.registerTool({name:'read_retirement_projection',title:'Read retirement projection',description:'Read the current saved or edited scenario projection and supported limitations without changing it.',inputSchema:{type:'object',properties:{year:{type:'integer'}},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(input===null||typeof input!=='object'||Array.isArray(input))throw Error('Expected an input object.');if(Object.keys(input).some(k=>k!=='year'))throw Error('Unknown property');const requestedYear='year' in input?input.year:undefined;const {workspace:w,result:r}=latest.current;if(!w||!r)throw Error('Open a valid plan first.');const p=w.scenarios.find(s=>s.id===w.activeId)!.plan;if(requestedYear!==undefined&&(typeof requestedYear!=='number'||!Number.isInteger(requestedYear)||requestedYear<p.startYear||requestedYear>p.endYear))throw Error('Year outside projection.');const row=r.rows.find((x)=>x.year===(requestedYear??p.people[0].retireYear));return {scenario:p.name,baseYear:p.baseYear,firstFailure:r.firstFailure,row:row?{year:row.year,portfolio:row.portfolio,realPortfolio:row.realPortfolio,accessible:row.accessible,federalTax:row.federalTax,payrollTax:row.payrollTax,spending:row.spending,magi:row.magi,shortfall:row.shortfall}:null,limits:limits.map(x=>x[0])};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[]);
 function changePlan(next:Plan){setWorkspace(w=>w?{...w,scenarios:w.scenarios.map(s=>s.id===w.activeId?{...s,plan:next}:s)}:w);}
 const save=useCallback(async()=>{if(!workspace)return;const problems=workspaceErrors(workspace);if(problems.length){setError(problems.join(' '));return;}setError('');try{await saveSession.save(JSON.stringify(workspace));}catch(cause){setError(cause instanceof Error?cause.message:'Save failed. Your draft is unchanged.');}},[workspace,saveSession]);
 useEffect(()=>{if(!autoSave||!workspace||!dirty||saving||saveState.blocked||workspaceErrors(workspace).length)return;const timer=setTimeout(()=>void save(),1500);return()=>clearTimeout(timer);},[autoSave,workspace,dirty,saving,saveState.blocked,save]);

 function copyDecision(next:Plan){if(!workspace||workspace.scenarios.length>=12)return;const id=crypto.randomUUID();setWorkspace({...workspace,activeId:id,scenarios:[...workspace.scenarios,{id,plan:structuredClone(next)}]});setPage('plan');}
 function addHandoffScenario(next:Plan){if(!workspace||workspace.scenarios.length>=12){setError('Export a backup and remove an unused scenario before adding another.');return;}const id=crypto.randomUUID();setWorkspace({...workspace,activeId:id,scenarios:[...workspace.scenarios,{id,plan:next}]});setPage('overview');}
 function duplicate(preset?:string){if(!workspace||!plan)return;const next=structuredClone(plan);next.name=newName.trim()||`${plan.name} copy`;if(preset==='buy'){next.housing.mode='buy';next.name='Buy a home';}if(preset==='later'){Object.assign(next,decisionPlan(plan,{delay:2}));next.name='Retire two years later';}if(preset==='real'){Object.assign(next,earlierReturnPlan(plan));}if(preset==='lower'){next.stockReturn=Math.max(-.99,next.stockReturn-.02);next.name='Lower market returns';}const id=crypto.randomUUID();setWorkspace({...workspace,activeId:id,scenarios:[...workspace.scenarios,{id,plan:next}]});setCreateOpen(false);setNewName('');setPage('scenarios');}
 async function importFile(file:File){setError('');try{if(file.size>1000000)throw Error('Choose a plan file under 1 MB.');let data:unknown=JSON.parse(await file.text());if(data&&typeof data==='object'&&'schema' in data&&data.schema===1)data={version:1,activeId:'imported',scenarios:[{id:'imported',plan:data}],notes:''};const problems=workspaceErrors(data);if(problems.length)throw Error(problems.join(' '));if(!validWorkspace(data))throw Error('Invalid workspace.');setImported(data);}catch(e){setError((e as Error).message);}if(fileInput.current)fileInput.current.value='';}
 function exportPlan(){if(workspace)download('snooks-retirement-plan.json',JSON.stringify(workspace,null,2));}
 if(loading&&!workspace)return <main className="loading-view"><div className="brand-icon"><BarChart3/></div><h1>Opening your saved plan</h1><p className="muted">Your household, timelines, and saved scenarios.</p></main>;
 if(!workspace||!plan)return <main className="loading-view"><ShieldCheck size={40}/><h1>{auth?'Your retirement plan is private':'Your plan could not be opened'}</h1><p role="alert">{error}</p>{auth?<a className="btn" href="/signin-with-chatgpt?return_to=%2F" target="_top">Sign in with ChatGPT</a>:<Button onClick={()=>void load()}>Try again</Button>}</main>;
 return <div className="app-shell"><header className="topbar"><button type="button" className="brand" onClick={()=>setPage('overview')}><span className="brand-icon"><BarChart3 size={22}/></span><span>snooks<span className="brand-sub">RETIREMENT PLANNER</span></span></button><div className="top-actions"><Button variant="ghost" size="sm" onClick={()=>setHelpOpen(true)}><HelpCircle size={16}/>Help</Button><span className="save-state"><Cloud size={16}/>{saving?'Saving…':dirty?'Unsaved changes':'Saved on this browser'}</span><Button onClick={save} disabled={saving||!dirty}><Save size={16}/>{saving?'Saving…':'Save plan'}</Button></div></header>
 <main className="workspace"><div className="notice info">Plans save only on this browser. Export a backup before switching devices or clearing browser data. <button type="button" onClick={()=>download('snooks-legacy-recovery.json',JSON.stringify(store.legacyBackup(),null,2))}>Export old-app recovery data</button></div><div className="workspace-heading"><div><span className="eyebrow">{plan.people.map((p)=>p.name).join(' + ')}</span><h1>Retirement outlook</h1></div><div className="scenario-switch"><Layers size={18}/><Select value={workspace.activeId} onValueChange={id=>setWorkspace({...workspace,activeId:id})}><SelectTrigger aria-label="Active scenario"><SelectValue/></SelectTrigger><SelectContent>{workspace.scenarios.map(s=><SelectItem key={s.id} value={s.id}>{s.plan.name}</SelectItem>)}</SelectContent></Select></div></div>
 <Tabs value={page} onValueChange={setPage}><div className="navigation compact-navigation"><Button variant="ghost" onClick={()=>setPage('overview')}>Outlook</Button><Button variant="outline" onClick={()=>setPage('plan')}>Edit plan</Button><div className="backup-actions"><Button variant="ghost" size="sm" onClick={exportPlan}><Download size={16}/>Export</Button><Button variant="ghost" size="sm" onClick={()=>fileInput.current?.click()}><Upload size={16}/>Import</Button><input hidden ref={fileInput} type="file" accept=".json,application/json" onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);}}/></div></div>
 <div className="draft-toolbar" aria-label="Draft editing tools"><div className="draft-actions"><Button variant="outline" size="sm" disabled={!history.past.length} onClick={()=>{loadGuard.markEdited();dispatchHistory({type:'undo'});}}>Undo</Button><Button variant="outline" size="sm" disabled={!history.future.length} onClick={()=>{loadGuard.markEdited();dispatchHistory({type:'redo'});}}>Redo</Button><label className="autosave-toggle"><input type="checkbox" aria-label="Automatically save valid drafts on this browser" checked={autoSave} onChange={event=>toggleAutoSave(event.target.checked)}/>Autosave</label></div><span className="small muted" role="status">{saving?'Saving captured draft…':saveState.blocked?'Autosave paused · retry Save plan or export and reload':dirty?(autoSave?'Changes waiting to save':'Unsaved draft'):'Saved'}{saveState.updatedAt&&<span> · Last saved {new Date(saveState.updatedAt).toLocaleString()}</span>}</span><Button variant="ghost" size="sm" onClick={()=>setPage('automation')}>Plan upkeep · {planChecks(plan).length} to review</Button></div>
 {error&&<div className="notice error" role="alert"><AlertTriangle size={18}/><div>{error}<div className="actions"><Button variant="outline" size="sm" onClick={exportPlan}>Export current draft</Button><Button variant="ghost" size="sm" onClick={()=>setReloadOpen(true)}>Reload saved version</Button></div></div></div>}
 {errors.length>0&&<div className="notice error" role="alert"><div><strong>Check these inputs before calculating or saving.</strong><ul>{errors.map((e:string)=><li key={e}>{e}</li>)}</ul><Button onClick={()=>setPage('plan')} variant="outline">Edit your plan</Button></div></div>}
 {projection.error&&<div className="notice error" role="alert"><div><strong>The projection could not finish.</strong><p>{projection.error}</p><p>Your inputs and saved scenarios are preserved.</p><div className="actions"><Button variant="outline" onClick={()=>setPage('plan')}>Review inputs</Button><Button variant="ghost" onClick={exportPlan}>Export current draft</Button></div></div></div>}
 {/* A modal detail drawer must not destroy the overview or its running test. */}
 {result&&<DecisionDashboard key={workspace.activeId} plan={plan} result={result} onChange={changePlan} onCopy={addHandoffScenario} canCopy={workspace.scenarios.length<12} onDeepDive={setPage} year={safeYear} onYear={setYear}/>}
 <Sheet open={page!=='overview'} onOpenChange={open=>{if(!open)setPage('overview');}}><SheetContent side="right" className="planner-drawer" showCloseButton={false}><div className="drawer-chrome"><SheetHeader><div className="drawer-title-row"><SheetTitle>{sections.find(([key])=>key===page)?.[1]??'Plan details'}</SheetTitle><SheetClose asChild><Button size="icon" variant="ghost" aria-label="Close plan details"><X size={20}/></Button></SheetClose></div><SheetDescription>Detailed inputs and calculations for the active scenario. Save plan to keep edits.</SheetDescription></SheetHeader><div className="drawer-navigation"><Select value={page==='overview'?'plan':page} onValueChange={setPage}><SelectTrigger aria-label="Detailed planning section"><SelectValue/></SelectTrigger><SelectContent>{sections.filter(([key])=>key!=='overview').map(([key,label])=><SelectItem key={key} value={key}>{label}</SelectItem>)}</SelectContent></Select><Button disabled={!dirty||saving} onClick={save}>Save plan</Button></div></div><div className="drawer-body">
 <TabsContent value="automation"><AutomationCenter key={workspace.activeId} plan={plan} scenarioId={workspace.activeId} onCopy={copyDecision} onOpen={setPage} canCopy={workspace.scenarios.length<12}/></TabsContent>
 <TabsContent value="plan"><PlanEditor plan={plan} onChange={changePlan}/></TabsContent>
 <TabsContent value="tax"><TaxYear plan={plan} onChange={changePlan}/></TabsContent><TabsContent value="annual">{result&&<Annual real={real} onReal={setReal} plan={plan} result={result} onChange={changePlan} year={safeYear} onYear={setYear}/>}</TabsContent>
 <TabsContent value="withdrawals">{result&&<WithdrawalComparison plan={plan} onCopy={copyDecision} canCopy={workspace.scenarios.length<12}/>}</TabsContent>
 <TabsContent value="bridge">{result&&<Bridge plan={plan} result={result} year={safeYear} onYear={setYear} onEdit={()=>setPage('plan')}/>}</TabsContent>
 <TabsContent value="health"><Healthcare plan={plan} result={result} onChange={changePlan} year={safeYear} onYear={setYear}/></TabsContent>
 <TabsContent value="decisions">{result&&<Decisions plan={plan} onCopy={copyDecision} canCopy={workspace.scenarios.length<12}/>}</TabsContent>
 <TabsContent value="scenarios"><div className="stack"><div className="section-head"><div><h2>Compare decisions before making them</h2><p className="muted">Each scenario keeps its own inputs and yearly overrides.</p></div><Button disabled={workspace.scenarios.length>=12} onClick={()=>{setNewName(`${plan.name} copy`);setCreateOpen(true);}}>Duplicate scenario</Button></div><div className="preset-grid"><button disabled={workspace.scenarios.length>=12} onClick={()=>duplicate('buy')}><span className="eyebrow">HOUSING</span><strong>Rent or buy?</strong><span>Copy your plan with a home purchase</span></button><button disabled={workspace.scenarios.length>=12} onClick={()=>duplicate('later')}><span className="eyebrow">TIMING</span><strong>Two more working years</strong><span>Test the effect of retiring later</span></button><button disabled={workspace.scenarios.length>=12} onClick={()=>duplicate('lower')}><span className="eyebrow">MARKETS</span><strong>Lower-return future</strong><span>Reduce expected stock returns by 2 points</span></button><button disabled={workspace.scenarios.length>=12} onClick={()=>duplicate('real')}><span className="eyebrow">EARLIER FIRE PLAN</span><strong>7% real, then 5% real</strong><span>Preserve other inputs and compare stock returns</span></button></div>
 <div className="scenario-grid">{workspace.scenarios.map(s=>{let r:ProjectionResult;try{r=project(s.plan);}catch{return <section className="panel" key={s.id}><h3>{s.plan.name}</h3><p>Inputs need correction.</p></section>;}return <section className={`panel scenario-card ${s.id===workspace.activeId?'active':''}`} key={s.id}><div className="section-head"><h3>{s.plan.name}</h3>{s.id===workspace.activeId&&<span className="pill">Active</span>}</div><dl className="flow-list"><div><dt>Retirement</dt><dd>{s.plan.people[0].retireYear}</dd></div><div><dt>Entering retirement</dt><dd>{r.retirement?compact(r.retirement.openingRealPortfolio):'Outside horizon'}</dd></div><div><dt>First unfunded year</dt><dd className={r.firstFailure?'negative':''}>{r.firstFailure||'None in baseline'}</dd></div><div><dt>Housing</dt><dd>{s.plan.housing.mode==='buy'?'Buy':'Rent'}</dd></div><div><dt>Lifetime federal tax</dt><dd>{compact(r.rows.reduce((v:number,x)=>v+x.federalTax/x.inflationIndex,0))}</dd></div></dl><Button variant="outline" onClick={()=>{setWorkspace({...workspace,activeId:s.id});setPage('plan');}}>Edit scenario</Button></section>;})}</div>
 {result&&<section className="panel"><div className="section-head"><div><h3>Overlay another scenario</h3><p className="muted">Deterministic projections, in {plan.baseYear} dollars.</p></div><Select value={compareId||'none'} onValueChange={v=>setCompareId(v==='none'?'':v)}><SelectTrigger aria-label="Comparison scenario"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">No comparison</SelectItem>{workspace.scenarios.filter(s=>s.id!==workspace.activeId).map(s=><SelectItem key={s.id} value={s.id}>{s.plan.name}</SelectItem>)}</SelectContent></Select></div>{comparison&&compareResult&&(comparison.plan.startYear!==plan.startYear||comparison.plan.endYear!==plan.endYear||comparison.plan.baseYear!==plan.baseYear)?<p className="notice warning">Align the forecast years and budget dollar year to overlay these scenarios.</p>:<ProjectionChart rows={result.rows} compare={compareResult?.rows} year={safeYear} onYear={setYear} baseYear={plan.baseYear}/>}<p className="small muted">Home equity is excluded from this portfolio chart. It remains visible in the yearly ledger. Scenario comparisons here do not include simulation probabilities.</p></section>}
 <Button variant="ghost" className="delete-button" disabled={workspace.scenarios.length===1} onClick={()=>setDeleteOpen(true)}>Delete active scenario</Button></div></TabsContent>
 <TabsContent value="stress">{result&&<><StressCases plan={plan}/><StressTests plan={plan} projection={result}/></>}</TabsContent>
 <TabsContent value="review"><div className="stack"><div className="section-head"><div><h2>A plan is only as strong as its inputs</h2><p className="muted">Your editable assumptions and model scope are visible here.</p></div><div className="actions"><a href="/architecture.md" download="Snooks-Architecture.md" className="btn btn-secondary">Architecture &amp; model limits</a></div></div><FinanceSnapshot plan={plan} onCopy={copyDecision} canCopy={workspace.scenarios.length<12}/><ScenarioReconciliation plan={plan} scenarios={workspace.scenarios} activeId={workspace.activeId} year={safeYear}/><Assumptions plan={plan} onChange={changePlan}/><section className="panel"><h3>Supported calculations and limits</h3><dl className="limits-list">{limits.map(([title,text])=><div key={title}><dt>{title}</dt><dd>{text}</dd></div>)}</dl><p className="notice info">Remaining limits include full debt/529 schedules, mixed-basis multi-year Form 8606, monthly tax filing, comprehensive lifetime withdrawal optimization, detailed benefit claiming and automatic bank synchronization. Matched withdrawal comparisons and bridge proposals evaluate a bounded set of strategies; they do not prove a globally optimal plan.</p></section><section className="panel"><h3>Household notes</h3><Textarea value={workspace.notes} maxLength={20000} onChange={e=>setWorkspace({...workspace,notes:e.target.value})} placeholder="Decisions, questions, and source details to revisit…" aria-label="Household planning notes" rows={5}/></section>{result&&<section className="panel"><h3>Ledger check</h3><p>Largest annual reconciliation difference: {dollars(Math.max(...result.rows.map((r)=>Math.abs(r.reconciliation))))}. A gap is reported separately and never hidden by later recovery.</p></section>}</div></TabsContent>
 </div></SheetContent></Sheet></Tabs><footer className="app-footer"><span><ShieldCheck size={15}/>On-device workspace · Export backups</span><span>Annual planning model · Review assumptions before acting</span></footer></main>
 <Dialog open={helpOpen} onOpenChange={setHelpOpen}><DialogContent><DialogHeader><DialogTitle>Use Snooks whenever you need it</DialogTitle><DialogDescription>Open snooks.vercel.app in your browser. Your plans stay on this browser and device; no financial information is sent to a server.</DialogDescription></DialogHeader><p>Bookmark this page on your PC. On iPhone, open it in Safari, use Share, then Add to Home Screen for a shortcut. An internet connection is required to load the application.</p><p>Use Save plan after editing. Use Export and Import to move saved scenarios between devices. Clearing browser data removes local saved plans. Export a JSON backup before major changes; leaving with unsaved edits can lose them.</p><p>Today’s dollars means purchasing power in your plan’s base year. The graph and annual ledger show year-end balances; Entering retirement shows the balance before the first retirement year.</p><p>Use Why this result? to inspect a funding gap. Use Decisions for the same-path retirement/budget comparison, Bridge for access timing, and Healthcare for dated coverage estimates. Copies preserve your original scenario.</p><DialogFooter><Button onClick={()=>setHelpOpen(false)}>Got it</Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent><DialogHeader><DialogTitle>Duplicate your scenario</DialogTitle><DialogDescription>Copy all inputs and annual overrides, then adjust the new plan.</DialogDescription></DialogHeader><label className="field">New scenario name<Input value={newName} onChange={e=>setNewName(e.target.value)} maxLength={120}/></label><DialogFooter><Button variant="outline" onClick={()=>setCreateOpen(false)}>Cancel</Button><Button disabled={!newName.trim()} onClick={()=>duplicate()}>Create copy</Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={!!imported} onOpenChange={v=>{if(!v)setImported(null);}}><DialogContent><DialogHeader><DialogTitle>Import this workspace?</DialogTitle><DialogDescription>This replaces the current draft with {imported?.scenarios.length} validated scenarios. Export your current workspace first if you want to keep it.</DialogDescription></DialogHeader><p>{imported?.scenarios.map(s=>s.plan.name).join(', ')}</p><DialogFooter><Button variant="outline" onClick={exportPlan}>Export current draft</Button><Button variant="outline" onClick={()=>setImported(null)}>Cancel</Button><Button onClick={()=>{setWorkspace(imported);setImported(null);setError('');}}>Import draft</Button></DialogFooter></DialogContent></Dialog>
 <AlertDialog open={deleteOpen} onOpenChange={setDeleteOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete “{plan.name}”?</AlertDialogTitle><AlertDialogDescription>Its inputs and annual overrides will be removed from your draft. Save the workspace to commit the deletion.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep scenario</AlertDialogCancel><AlertDialogAction onClick={()=>{const scenarios=workspace.scenarios.filter(s=>s.id!==workspace.activeId);setWorkspace({...workspace,scenarios,activeId:scenarios[0].id});setCompareId('');}}>Delete scenario</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={reloadOpen} onOpenChange={setReloadOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Reload the saved workspace?</AlertDialogTitle><AlertDialogDescription>Your unsaved edits will be replaced. Export the current draft first if you want to preserve it.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep editing</AlertDialogCancel><AlertDialogAction disabled={saving} onClick={()=>void load()}>Reload saved version</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
