'use client';
import {useMemo,useState} from 'react';
import {reconcileScenarios} from '../../engine/scenario-reconciliation.mjs';
import {createHandoffPlan} from '../../engine/handoff.mjs';
import {Button} from '@/components/ui/button';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {dollars,download} from './format';
import type {Plan} from './model-types';
const inputValue=(present:boolean,value:unknown)=>!present?'Not entered':JSON.stringify(value);
export default function ScenarioReconciliation({plan,scenarios,activeId,year}:{plan:Plan;scenarios:{id:string;plan:Plan}[];activeId:string;year:number}){
 const [selection,setSelection]=useState('reference:handoff'),[filter,setFilter]=useState('all');
 const handoff=useMemo(()=>createHandoffPlan(),[]);
 const reference=selection==='reference:handoff'?handoff:scenarios.find(s=>`scenario:${s.id}`===selection&&s.id!==activeId)?.plan;
 const comparison=useMemo(()=>{if(!reference)return {result:null,error:''};try{return {result:reconcileScenarios(plan,reference),error:''};}catch(error){return {result:null,error:error instanceof Error?error.message:String(error)};}},[plan,reference]);
 const result=comparison.result,groups=result?[...new Set(result.differences.map(diff=>diff.group))]:[];
 const differences=result?.differences.filter(diff=>filter==='all'||diff.group===filter)??[];
 const row=result?.years.find(row=>row.year===year)??result?.years[0];
 return <section className="panel"><div className="section-head"><div><h3>Why do these projections differ?</h3><p className="muted">Compare the active draft with another saved scenario or your supplied handoff. Every financial input stays unchanged.</p></div><Select value={reference?selection:'none'} onValueChange={value=>{setSelection(value);setFilter('all');}}><SelectTrigger aria-label="Reconciliation reference"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Choose a reference</SelectItem><SelectItem value="reference:handoff">Your October handoff inputs</SelectItem>{scenarios.filter(s=>s.id!==activeId).map(s=><SelectItem key={s.id} value={`scenario:${s.id}`}>{s.plan.name}</SelectItem>)}</SelectContent></Select></div>
 {comparison.error&&<p className="notice error" role="alert">{comparison.error}</p>}
 {result&&<><p className={`notice ${result.identicalInputs?'info':'warning'}`}>{result.identicalInputs?'The forward-calculation inputs match.':'These calculation inputs differ. Check their units and timing before interpreting the results.'} {result.differences.length} differing input values. Names, evidence notes and the separate current-year tax sandbox are excluded from this comparison.</p>
 <div className="two-columns">{[result.left,result.right].map((summary,index)=><div key={index}><h4>{index===0?'Active draft':'Reference'} · {summary.name}</h4><dl className="flow-list"><div><dt>Forecast / purchasing-power year</dt><dd>{summary.startYear}–{summary.endYear} / {summary.baseYear}</dd></div><div><dt>Entering first retirement ({summary.retirementYear})</dt><dd>{summary.retirementOpening===null?'Outside forecast':dollars(summary.retirementOpening)}</dd></div><div><dt>Financial assets at forecast end</dt><dd>{dollars(summary.terminal)}</dd></div><div><dt>First unfunded year</dt><dd>{summary.firstFailure??'None in baseline'}</dd></div></dl></div>)}</div>
 {!result.aligned?<p className="notice warning">Forecast dates or purchasing-power years differ. Dollar deltas and the annual comparison are withheld until these inputs match.</p>:<><p className="small muted">Reference minus active draft: {result.retirementDelta===null?'retirement-entry delta unavailable because retirement dates differ':`${dollars(result.retirementDelta)} entering retirement`}; {dollars(result.terminalDelta??0)} at forecast end. These are combined effects, not an additive attribution of individual assumptions.</p>{row&&<details><summary>{row.year} annual comparison · {plan.baseYear} dollars</summary><Table><TableHeader><TableRow>{['Measure','Active draft','Reference','Difference'].map(label=><TableHead key={label}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{row.metrics.map(metric=><TableRow key={metric.label}><TableCell>{metric.label}</TableCell><TableCell>{dollars(metric.left)}</TableCell><TableCell>{dollars(metric.right)}</TableCell><TableCell>{dollars(metric.delta)}</TableCell></TableRow>)}</TableBody></Table><p className="small muted">End-of-year balances and annual flows are separate. Deposits include transfers; they are not extra income. Select a year on the main timeline to inspect that year here.</p></details>}</>}
 <details><summary>Inspect differing assumptions</summary><Select value={groups.includes(filter)?filter:'all'} onValueChange={setFilter}><SelectTrigger aria-label="Input difference category"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All input groups</SelectItem>{groups.map(group=><SelectItem key={group} value={group}>{group}</SelectItem>)}</SelectContent></Select><Table><TableHeader><TableRow>{['Input path','Group','Active draft','Reference'].map(label=><TableHead key={label}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{differences.slice(0,60).map(diff=><TableRow key={diff.path}><TableCell>{diff.path}</TableCell><TableCell>{diff.group}</TableCell><TableCell>{inputValue(diff.leftPresent,diff.left)}</TableCell><TableCell>{inputValue(diff.rightPresent,diff.right)}</TableCell></TableRow>)}</TableBody></Table>{differences.length>60&&<p className="small muted">Showing60 of{differences.length} differences. Export includes all of them.</p>}</details>
 <div className="actions"><Button variant="outline" onClick={()=>download('snooks-scenario-reconciliation.json',JSON.stringify({activeDraft:plan,reference,result,method:'Read-only deterministic comparison; input differences are not independent causal contributions'},null,2))}>Export inputs + comparison</Button></div><p className="small muted">This runs the same annual engine on both input sets. A balancing ledger checks conservation; it does not independently certify tax rules or assumptions. The supplied handoff is not the unseen earlier chat’s formulas. Missing cost basis, healthcare quotes and provider permissions still need records.</p>
 </>}
 </section>;
}
