'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Progress} from '@/components/ui/progress';
import {Input} from '@/components/ui/input';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {startPlannerWorker} from './worker-client.mjs';
import workerUrl from './withdrawal.worker.ts?worker&url';
import {dollars,percent} from './format';
import type {Plan} from './model-types';

type StrategyRow={id:string;label:string;description:string;plan:Plan;successRate:number;withinBudgetSuccessRate:number;penaltyFreeRate:number;medianEnding:number;p10Ending:number;medianTaxAdjustedEnding:number;p10TaxAdjustedEnding:number;meanRealTerminalTax:number;meanRealIncomeTax:number;meanRealPenalty:number;meanRealHealthcare:number;medianRealCuts:number;improvedPaths:number;worsePaths:number;rank:number};
type Comparison={rows:StrategyRow[];bestId:string;count:number;seed:number;mode:string;terminalValuation:{mode:'gross'|'tax_adjusted';traditionalTaxRate:number;taxableGainTaxRate:number;hsaTaxRate:number};rankingRule:string;assumptions:string[]};
type Props={plan:Plan;canCopy:boolean;onCopy:(plan:Plan)=>void};
export default function WithdrawalComparison(props:Props){return <ComparisonSession key={JSON.stringify(props.plan)} {...props}/>;}
function ComparisonSession({plan,canCopy,onCopy}:Props){
 const [objective,setObjective]=useState('lower_tail'),[mode,setMode]=useState('montecarlo'),[output,setOutput]=useState<Comparison|null>(null),[progress,setProgress]=useState<number|null>(null),[error,setError]=useState('');
 const [count,setCount]=useState('75'),[valuationMode,setValuationMode]=useState<'gross'|'tax_adjusted'>('gross');
 const [traditionalRate,setTraditionalRate]=useState('22'),[gainRate,setGainRate]=useState('15'),[hsaRate,setHsaRate]=useState('22');
 const ratesValid=[traditionalRate,gainRate,hsaRate].every(value=>value.trim()!==''&&Number.isFinite(Number(value))&&Number(value)>=0&&Number(value)<=100);
 const worker=useRef<{cancel:()=>void}|null>(null);
 useEffect(()=>()=>worker.current?.cancel(),[]);
 function clear(){worker.current?.cancel();worker.current=null;setProgress(null);setOutput(null);setError('');}
 function run(){if(!ratesValid)return;clear();setProgress(0);worker.current=startPlannerWorker(workerUrl,{plan,options:{count:Number(count),seed:2026,mode,objective,inflationMode:mode==='bootstrap'?'historical':'fixed',terminalValuation:{mode:valuationMode,traditionalTaxRate:Number(traditionalRate)/100,taxableGainTaxRate:Number(gainRate)/100,hsaTaxRate:Number(hsaRate)/100}}},{onProgress:(v:number)=>setProgress(v*100),onResult:(result:Comparison)=>{setOutput(result);setProgress(null);worker.current=null;},onError:(message:string)=>{setError(message);setProgress(null);worker.current=null;}});}
 const best=output?.rows.find(row=>row.id===output.bestId);
 return <div className="stack"><section className="panel"><h2>Compare withdrawal policies</h2><p>Try fixed funding policies against identical return and inflation paths. The comparison includes your saved policy, different account orders, and conversion-cap changes; it does not rewrite your plan.</p>
 <div className="field-grid"><label className="field">Market paths<Select value={mode} onValueChange={v=>{clear();setMode(v);}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="montecarlo">Monte Carlo</SelectItem><SelectItem value="bootstrap">Historical resampling</SelectItem></SelectContent></Select></label>
 <label className="field">Matched path count<Select value={count} onValueChange={v=>{clear();setCount(v);}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['50','75','150','300','500'].map(value=><SelectItem key={value} value={value}>{value}{value==='75'?' · quick comparison':''}</SelectItem>)}</SelectContent></Select></label>
 <label className="field">Tie-break objective<Select value={objective} onValueChange={v=>{clear();setObjective(v);}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="lower_tail">Protect poorer terminal outcomes</SelectItem><SelectItem value="median">Favor median terminal wealth</SelectItem></SelectContent></Select></label>
 <label className="field">Terminal wealth valuation<Select value={valuationMode} onValueChange={v=>{clear();setValuationMode(v as 'gross'|'tax_adjusted');}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="gross">Gross account balances</SelectItem><SelectItem value="tax_adjusted">Illustrative after-tax value</SelectItem></SelectContent></Select></label></div>
 <p className="small muted">Funding all bills ranks first, then funding the requested budget without cuts. The selected wealth valuation only changes the tie-break. Both gross and illustrative after-tax values are reported; these settings affect this comparison only.</p>
 <details><summary>Illustrative terminal tax assumptions</summary><p className="small muted">Fixed planning haircuts, not an actual liquidation quote. Traditional and SEPP balances use the traditional rate. Brokerage taxes apply only to positive unrealized gains, not cost basis. Roth is assumed tax-free here, even though nonqualified early withdrawals can have tax or penalties. HSA medical withdrawals can be tax-free; enter 0% if that matches your terminal planning assumption.</p><div className="field-grid">
 <label className="field">Traditional / SEPP burden (%)<Input type="number" min="0" max="100" step="1" inputMode="decimal" value={traditionalRate} onChange={e=>{clear();setTraditionalRate(e.target.value);}}/></label>
 <label className="field">Taxable gain burden (%)<Input type="number" min="0" max="100" step="1" inputMode="decimal" value={gainRate} onChange={e=>{clear();setGainRate(e.target.value);}}/></label>
 <label className="field">HSA burden (%)<Input type="number" min="0" max="100" step="1" inputMode="decimal" value={hsaRate} onChange={e=>{clear();setHsaRate(e.target.value);}}/></label></div><p className="small muted">Defaults of 22%, 15% and 22% are illustrative choices, not verified future tax rates. Cash and Roth receive no haircut, and taxable losses do not create a tax credit. This estimate does not model future brackets, state taxes, ACA effects or immediate account access.</p></details>
 {!ratesValid&&<p role="alert" className="notice error">Enter a terminal tax burden from 0% to 100% for each account category.</p>}
 <div className="actions"><Button disabled={progress!==null||!ratesValid} onClick={run}>{progress===null?'Compare policies':'Comparing…'}</Button>{progress!==null&&<Button variant="outline" onClick={clear}>Cancel</Button>}</div>{progress!==null&&<Progress value={progress}/>} {error&&<p role="alert" className="notice error">{error}</p>}
 {output&&best&&<div className="notice info"><strong>Best among these tested policies: {best.label}</strong><p>{output.rankingRule}</p><p>{percent(best.withinBudgetSuccessRate)} of {output.count} sampled paths funded the requested budget without spending cuts or protected-cost overruns. This sample is a comparison, not certainty or a globally optimal strategy.</p><Button disabled={!canCopy} variant="outline" onClick={()=>onCopy(best.plan)}>Create comparison scenario</Button></div>}
 </section>
 {output&&<section className="panel"><h3>Results on the same paths</h3><p className="small muted">Wealth tie-break uses {output.terminalValuation.mode==='gross'?'gross balances':'illustrative after-tax values'}. Both figures below are in {String(plan.baseYear)} purchasing power.</p>
 <div className="stack md:hidden">{output.rows.map(row=><article key={row.id} className="panel"><h4>{row.label}</h4><p className="small muted">{row.description}</p><dl className="grid grid-cols-2 gap-3 text-sm">{[
 ['Bills funded',percent(row.successRate)],['Full budget funded',percent(row.withinBudgetSuccessRate)],['Penalty-free funding',percent(row.penaltyFreeRate)],['Paths improved / worse',`${percent(row.improvedPaths)} / ${percent(row.worsePaths)}`],
 ['10th-percentile · gross',dollars(row.p10Ending)],['10th-percentile · after-tax estimate',dollars(row.p10TaxAdjustedEnding)],['Median · gross',dollars(row.medianEnding)],['Median · after-tax estimate',dollars(row.medianTaxAdjustedEnding)],
 ['Mean income tax',dollars(row.meanRealIncomeTax)],['Mean additional tax',dollars(row.meanRealPenalty)],['Mean healthcare',dollars(row.meanRealHealthcare)],['Median spending cuts',dollars(row.medianRealCuts)]
 ].map(([label,value])=><div key={label}><dt className="muted">{label}</dt><dd>{value}</dd></div>)}</dl><Button size="sm" variant="outline" disabled={!canCopy} onClick={()=>onCopy(row.plan)}>Copy policy</Button></article>)}</div>
 <div className="hidden md:block"><Table><TableHeader><TableRow>{['Policy','Bills funded','Full budget funded','Penalty-free funding','10th-percentile ending assets','Median ending assets','Mean income tax','Mean additional tax','Mean healthcare','Median spending cuts','Paths improved / worse'].map(label=><TableHead key={label}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{output.rows.map(row=><TableRow key={row.id}><TableCell><strong>{row.label}</strong><p className="small muted">{row.description}</p><Button size="sm" variant="outline" disabled={!canCopy} onClick={()=>onCopy(row.plan)}>Copy policy</Button></TableCell><TableCell>{percent(row.successRate)}</TableCell><TableCell>{percent(row.withinBudgetSuccessRate)}</TableCell><TableCell>{percent(row.penaltyFreeRate)}</TableCell><TableCell>{dollars(row.p10Ending)} gross<p className="small muted">{dollars(row.p10TaxAdjustedEnding)} after-tax estimate</p></TableCell><TableCell>{dollars(row.medianEnding)} gross<p className="small muted">{dollars(row.medianTaxAdjustedEnding)} after-tax estimate</p></TableCell>{[row.meanRealIncomeTax,row.meanRealPenalty,row.meanRealHealthcare,row.medianRealCuts].map((value,i)=><TableCell key={i}>{dollars(value)}</TableCell>)}<TableCell>{percent(row.improvedPaths)} / {percent(row.worsePaths)}</TableCell></TableRow>)}</TableBody></Table></div>
 <p className="small muted">Tax, additional tax, healthcare and cuts are cumulative over the modeled horizon. Terminal after-tax estimates use fixed account haircuts and are not additional outflows in the simulation. Paths improved/worse compare outcomes with your configured policy; a zero change can be a tie. Household expenses, medical assumptions and account restrictions remain unchanged.</p><details><summary>Comparison assumptions</summary><ul>{output.assumptions.map((assumption,i)=><li key={i}>{assumption}</li>)}</ul></details></section>}
 </div>;
}
