import {Button} from '@/components/ui/button';
import {dollars} from './format';
import type {Plan,ProjectionRow} from './model-types';

export default function YearSnapshot({plan,row,onYear,onInspect}:{plan:Plan;row:ProjectionRow;onYear:(year:number)=>void;onInspect:()=>void}){
 const index=row.inflationIndex,amount=(value:number)=>dollars(value/index);
 const sum=(key:'brokerage'|'traditional'|'roth'|'cash'|'hsa'|'sepp'|'unvested')=>row.accounts.reduce((total,account)=>total+(account[key]??0),0);
 const balances:[string,number][]=[['Taxable brokerage',sum('brokerage')],['Traditional retirement',sum('traditional')],['Roth accounts',sum('roth')],['Cash reserve',sum('cash')],['HSA',sum('hsa')],['SEPP account',sum('sepp')]];
 const reserveGap=row.reserveShortfall??0;
 return <section className="year-snapshot" aria-label={`Account snapshot for ${row.year}`}>
  <div className="section-head"><div><h3>{row.year} at a glance</h3><p className="small muted">Baseline · end-of-year balances · {plan.baseYear} purchasing power</p></div><div className="year-navigation" role="group" aria-label="Inspect a year"><Button variant="outline" size="sm" aria-label="Previous year" disabled={row.year<=plan.startYear} onClick={()=>onYear(row.year-1)}>←</Button><Button variant="outline" size="sm" aria-label="Next year" disabled={row.year>=plan.endYear} onClick={()=>onYear(row.year+1)}>→</Button><Button variant="ghost" size="sm" onClick={()=>onYear(Math.min(plan.endYear,Math.max(plan.startYear,Math.min(...plan.people.map(person=>person.retireYear)))))}>Retirement year</Button></div></div>
  <dl className="snapshot-totals"><div><dt>Financial assets</dt><dd>{amount(row.portfolio)}</dd></div><div><dt>Available without early-withdrawal penalties</dt><dd>{amount(row.accessible)}</dd></div><div><dt>Home equity</dt><dd>{amount(row.homeEquity)}</dd></div></dl>
  <details><summary>Account balances and cash flow</summary><div className="snapshot-breakdown"><dl className="flow-list">{balances.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{amount(value)}</dd></div>)}</dl><dl className="flow-list">{([['Gross pay',row.wages],['Federal + payroll tax, including penalties',row.federalTax+row.payrollTax],['Total outgo, including one-time costs',row.totalOutgo],['Account withdrawals',row.peopleFlow.reduce((total,person)=>total+person.withdrawals,0)],['Remaining funding gap',row.shortfall],['Unfilled cash reserve',reserveGap]] as [string,number][]).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{amount(value)}</dd></div>)}</dl></div><p className="small muted">Penalty-free access is before income tax and is part of financial assets. Home equity cannot directly pay bills. HSA use is restricted; permitted early distributions can still help fund spending. {sum('unvested')>1?`${amount(sum('unvested'))} of traditional assets is unvested.`:''} Transfers and withdrawals are not additional income.</p></details>
  <div className="snapshot-status"><span className={row.shortfall>1?'negative':reserveGap>1?'warning':'muted'}>{row.shortfall>1?`${amount(row.shortfall)} remains unfunded after permitted withdrawals.`:reserveGap>1?`Bills funded; cash reserve is ${amount(reserveGap)} below target.`:(row.earlyWithdrawalPenalty??0)>1?`Bills funded with ${amount(row.earlyWithdrawalPenalty)} in early-withdrawal penalties.`:'All modeled bills funded for this year.'}</span><Button variant="outline" size="sm" onClick={onInspect}>Open {row.year} ledger</Button></div>
 </section>;
}
